from pathlib import Path
import json

p = Path('C:/Users/Admin/Desktop/C-CPP/CPP/cpp_lessons.js')
s = p.read_text(encoding='utf-8')
marker = 'window.cppLessons=lessons;'
if marker not in s:
    raise SystemExit('lesson assignment marker not found')


def item(id, title, chapter, concept, syntax, code, output, explanation, prerequisites=()):
    return dict(id=id, title=title, chapter=chapter, concept=concept, syntax=syntax, code=code, output=output, explanation=explanation, prerequisites=list(prerequisites))

items = [
item('cpp-namespace','Namespaces','01 · C++ Basics','Namespace tạo vùng tên để tránh xung đột giữa các hàm, class và biến có cùng tên. Thư viện chuẩn nằm trong namespace std; viết std:: giúp compiler biết chính xác symbol nào được dùng.','#include <iostream>\nnamespace app { void greet(); }','#include <iostream>\nnamespace app { void greet() { std::cout << "Hello"; } }\nint main() { app::greet(); }','Hello','greet thuộc app nên được gọi bằng app::greet().',['cpp-intro']),
item('cpp-newline','\\n và std::endl','01 · C++ Basics','Cả ký tự newline và std::endl đều xuống dòng. std::endl còn flush stream, nên dùng nó khi thật sự cần đẩy buffer ngay; trong output thường xuyên, \\n thường hiệu quả hơn.','std::cout << "text\\n";\nstd::cout << "text" << std::endl;','#include <iostream>\nint main() { std::cout << "A\\nB\\n"; }','A\nB','\\n xuống dòng mà không yêu cầu flush mỗi lần.',['cpp-output']),
item('cpp-stream-state','Trạng thái stream','01 · C++ Basics','std::cin có các trạng thái good, fail, eof và bad. Khi input sai kiểu, stream bật failbit; cần clear() rồi loại phần dữ liệu sai trước khi đọc tiếp.','if (std::cin.fail()) { std::cin.clear(); std::cin.ignore(...); }','#include <iostream>\n#include <limits>\nint main() {\n    int n;\n    if (!(std::cin >> n)) {\n        std::cin.clear();\n        std::cin.ignore(std::numeric_limits<std::streamsize>::max(), \'\\n\');\n        std::cout << "Invalid";\n    }\n}','Invalid','clear xóa cờ lỗi; ignore bỏ dữ liệu còn lại của dòng.',['cpp-input']),
item('cpp-enum-class','enum class','01 · C++ Basics','enum class tạo tập hằng có phạm vi và kiểu an toàn hơn enum kiểu cũ. Thành viên không tự chuyển thành int, vì vậy code tránh được nhiều phép so sánh nhầm.','enum class Color { red, green };\nColor color = Color::green;','#include <iostream>\nenum class Color { Red, Green };\nint main() { Color color = Color::Green; if (color == Color::Green) std::cout << "green"; }','green','Phải dùng Color::Green để truy cập thành viên có phạm vi.',['cpp-if']),
item('cpp-auto','auto và suy luận kiểu','02 · Values and Control','auto yêu cầu compiler suy luận kiểu từ biểu thức khởi tạo. Nó giảm lặp tên kiểu dài, nhưng không làm biến trở thành kiểu động; kiểu vẫn cố định sau khi biên dịch.','auto name = initializer;','#include <iostream>\n#include <vector>\nint main() { std::vector<int> values{1,2,3}; auto count = values.size(); std::cout << count; }','3','count có kiểu size_type được suy luận từ values.size().',['cpp-types']),
item('cpp-const-ref','const reference','02 · Values and Control','const T& cho phép đọc object lớn mà không sao chép và không cho hàm sửa object qua tham chiếu đó. Đây là kiểu tham số phổ biến cho string, vector và class.','void print(const T& value);','#include <iostream>\n#include <string>\nvoid print(const std::string& text) { std::cout << text; }\nint main() { print("C++"); }','C++','const reference đọc dữ liệu mà không tạo bản sao string.',['cpp-functions']),
item('cpp-ternary','Toán tử điều kiện ?:','02 · Values and Control','Toán tử ba ngôi chọn một trong hai biểu thức dựa trên điều kiện. Nó phù hợp cho lựa chọn ngắn; nếu nhánh dài, dùng if để dễ đọc hơn.','condition ? value_if_true : value_if_false','#include <iostream>\nint main() { int n=7; std::cout << (n%2==0 ? "Even" : "Odd"); }','Odd','Điều kiện đúng chọn biểu thức trước dấu :.',['cpp-comparison']),
item('cpp-switch-enum','switch với enum class','03 · Control Flow','enum class kết hợp switch tạo menu/trạng thái có tên rõ ràng. Mỗi case dùng tên đủ phạm vi và nên có default để xử lý giá trị ngoài dự kiến.','switch (state) { case State::ready: ... }','#include <iostream>\nenum class State { Ready, Done };\nint main() { State state=State::Done; switch(state){case State::Ready: std::cout<<"ready"; break; case State::Done: std::cout<<"done"; break;} }','done','switch so sánh các giá trị enum class mà không cần dùng số ma thuật.',['cpp-enum-class']),
item('cpp-array','std::array','04 · STL Containers','std::array<T,N> là container có kích thước cố định, lưu liên tiếp như mảng C nhưng cung cấp size(), begin/end và giao tiếp tốt với STL.','std::array<T,N> values{...};','#include <array>\n#include <iostream>\nint main(){ std::array<int,3> a{2,4,6}; std::cout<<a.size()<<" "<<a[1]; }','3 4','std::array biết kích thước và dùng được với algorithms.',['cpp-vector']),
item('cpp-deque','std::deque','04 · STL Containers','deque là hàng đợi hai đầu, cho phép thêm/xóa hiệu quả ở front và back. Không nên giả định toàn bộ phần tử nằm trong một vùng nhớ liên tiếp như vector.','std::deque<T> q;\npush_front/push_back','#include <deque>\n#include <iostream>\nint main(){ std::deque<int> q{2,3}; q.push_front(1); q.push_back(4); for(int x:q)std::cout<<x<<" "; }','1 2 3 4 ','deque phù hợp khi cần thêm ở cả hai đầu.',['cpp-vector']),
item('cpp-list','std::list','04 · STL Containers','list là danh sách liên kết hai chiều. Chèn/xóa tại iterator đã biết không di chuyển các node khác, nhưng truy cập theo index chậm hơn vector/deque.','std::list<T> values;\nvalues.insert(it,value);','#include <iostream>\n#include <list>\nint main(){ std::list<int> values{1,3}; auto it=values.begin(); ++it; values.insert(it,2); for(int x:values)std::cout<<x<<" "; }','1 2 3 ','list giữ iterator hợp lệ khi chèn node mới.',['cpp-iterators']),
item('cpp-stack','std::stack','04 · STL Containers','stack là container adapter theo nguyên tắc LIFO: phần tử vào sau được lấy ra trước. Nó cung cấp push, pop, top và empty, không cho duyệt trực tiếp.','std::stack<T> stack;\nstack.push(value);\nstack.top();','#include <iostream>\n#include <stack>\nint main(){ std::stack<int> s; s.push(1); s.push(2); std::cout<<s.top(); s.pop(); }','2','top xem phần tử trên cùng; pop loại bỏ nhưng không trả giá trị.',['cpp-vector']),
item('cpp-queue','std::queue','04 · STL Containers','queue là adapter FIFO: phần tử vào trước được lấy ra trước. front xem đầu hàng, back xem cuối hàng; push thêm cuối và pop loại đầu.','std::queue<T> q;\nq.push(value);\nq.front();','#include <iostream>\n#include <queue>\nint main(){ std::queue<int> q; q.push(10); q.push(20); std::cout<<q.front(); q.pop(); std::cout<<q.front(); }','1020','Hai phần tử được lấy theo đúng thứ tự đưa vào.',['cpp-vector']),
item('cpp-priority-queue','std::priority_queue','04 · STL Containers','priority_queue luôn đưa phần tử có độ ưu tiên cao nhất lên top. Mặc định là max-heap; có thể truyền comparator để tạo min-heap hoặc thứ tự riêng.','std::priority_queue<T> pq;\npq.top();','#include <iostream>\n#include <queue>\nint main(){ std::priority_queue<int> pq; pq.push(3); pq.push(9); pq.push(5); std::cout<<pq.top(); }','9','Phần tử lớn nhất được ưu tiên mặc định.',['cpp-queue']),
item('cpp-unordered-map','std::unordered_map','04 · STL Containers','unordered_map lưu key-value bằng bảng băm. Tìm kiếm trung bình O(1), nhưng không giữ thứ tự key; cần hash và equality phù hợp.','std::unordered_map<Key,Value> data;','#include <iostream>\n#include <unordered_map>\n#include <string>\nint main(){ std::unordered_map<std::string,int> m{{"An",9}}; m["Binh"]=8; std::cout<<m.at("An"); }','9','at đọc key và ném exception nếu key không tồn tại; operator[] có thể tạo entry mới.',['cpp-map-set']),
item('cpp-unordered-set','std::unordered_set','04 · STL Containers','unordered_set lưu các giá trị duy nhất bằng hash và không sắp xếp chúng. Dùng count hoặc find để kiểm tra phần tử có tồn tại.','std::unordered_set<T> values;\nvalues.insert(value);','#include <iostream>\n#include <unordered_set>\nint main(){ std::unordered_set<int> s{2,2,3}; std::cout<<s.size()<<" "<<s.count(3); }','2 1','Hai số 2 chỉ tạo một phần tử duy nhất.',['cpp-map-set']),
item('cpp-tuple','std::tuple','04 · STL Containers','tuple nhóm nhiều giá trị có thể khác kiểu. std::get<index> truy cập theo vị trí; structured binding thường làm code đọc dễ hơn.','std::tuple<T1,T2> value{...};\nstd::get<0>(value);','#include <iostream>\n#include <tuple>\nint main(){ std::tuple<std::string,int> user{"An",20}; std::cout<<std::get<0>(user)<<" "<<std::get<1>(user); }','An 20','get truy cập trường theo index compile-time.',['cpp-map-set']),
item('cpp-optional','std::optional','04 · STL Containers','optional biểu diễn một giá trị có thể có hoặc không có mà không cần dùng sentinel như -1. Kiểm tra has_value hoặc dùng value_or trước khi lấy giá trị.','std::optional<T> find();\nif (value) { ... }','#include <iostream>\n#include <optional>\nstd::optional<int> findScore(bool found){ if(found)return 9; return std::nullopt; }\nint main(){ std::cout<<findScore(true).value_or(0); }','9','optional giữ rõ trường hợp “không có kết quả”.',['cpp-functions']),
item('cpp-variant','std::variant','04 · STL Containers','variant giữ một giá trị thuộc một trong các kiểu đã khai báo và biết kiểu hiện tại. std::visit xử lý giá trị mà không cần union thủ công.','std::variant<int,std::string> value;\nstd::visit(visitor,value);','#include <iostream>\n#include <variant>\n#include <string>\nint main(){ std::variant<int,std::string> value=std::string("text"); std::visit([](const auto& x){std::cout<<x;},value); }','text','visit gọi lambda phù hợp với alternative hiện tại.',['cpp-optional']),
item('cpp-string-view','std::string_view','04 · STL Containers','string_view là view không sở hữu một dãy ký tự. Nó tránh sao chép khi chỉ cần đọc, nhưng view phải ngắn hơn hoặc bằng lifetime của string gốc.','std::string_view view{text};','#include <iostream>\n#include <string_view>\nvoid print(std::string_view text){ std::cout<<text; }\nint main(){ print("C++ view"); }','C++ view','String literal sống đủ lâu trong lời gọi; hàm chỉ đọc view.',['cpp-string']),
item('cpp-span','std::span','04 · STL Containers','span là view không sở hữu trên vùng phần tử liên tiếp, dùng chung cho vector, array và mảng C. Nó truyền pointer cùng length mà không copy dữ liệu.','std::span<T> values;','#include <iostream>\n#include <span>\nvoid sum(std::span<const int> a){int total=0;for(int x:a)total+=x;std::cout<<total;}\nint main(){int a[]{1,2,3};sum(a);}','6','span nhận mảng và biết số phần tử qua extent runtime.',['cpp-array']),
item('cpp-count-find','count và find','08 · STL Algorithms','std::count đếm số lần xuất hiện; std::find trả iterator tới phần tử đầu tiên hoặc end nếu không thấy. Cả hai làm việc trên iterator range.','std::count(first,last,value);\nstd::find(first,last,value);','#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){std::vector<int> v{1,2,2,3};std::cout<<std::count(v.begin(),v.end(),2)<<" "<<(std::find(v.begin(),v.end(),3)!=v.end());}','2 1','count trả số lượng; find trả vị trí để tiếp tục xử lý.',['cpp-algorithms']),
item('cpp-max-element','max_element và min_element','08 · STL Algorithms','max_element/min_element trả iterator tới phần tử lớn nhất/nhỏ nhất trong range. Range rỗng không có phần tử hợp lệ nên cần kiểm tra trước khi dereference.','auto it = std::max_element(begin,end);','#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){std::vector<int> v{4,9,2};auto it=std::max_element(v.begin(),v.end());std::cout<<*it;}','9','Dereference iterator sau khi bảo đảm range không rỗng.',['cpp-algorithms']),
item('cpp-accumulate','accumulate và reduce','08 · STL Algorithms','accumulate trong numeric gộp các phần tử theo thứ tự, thường dùng tính tổng. reduce có thể thay đổi thứ tự kết hợp và thích hợp phép toán associative, đặc biệt khi song song hóa.','std::accumulate(begin,end,initial);','#include <iostream>\n#include <numeric>\n#include <vector>\nint main(){std::vector<int> v{1,2,3,4};std::cout<<std::accumulate(v.begin(),v.end(),0);}','10','Giá trị ban đầu 0 quyết định kiểu và kết quả tích lũy.',['cpp-algorithms']),
item('cpp-transform','transform','08 · STL Algorithms','transform áp dụng một phép biến đổi cho từng phần tử và ghi vào output range. Nó tách thuật toán khỏi container và tránh viết loop thủ công lặp lại.','std::transform(begin,end,out,operation);','#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){std::vector<int> v{1,2,3},out(3);std::transform(v.begin(),v.end(),out.begin(),[](int x){return x*x;});for(int x:out)std::cout<<x<<" ";}','1 4 9 ','Output iterator phải trỏ tới vùng đủ chỗ ghi.',['cpp-algorithms']),
item('cpp-remove-if','remove_if và erase','08 · STL Algorithms','remove_if dồn các phần tử không bị loại về đầu range và trả “new logical end”; container vẫn giữ kích thước cũ. Với vector, kết hợp erase để xóa phần đuôi thực sự.','values.erase(std::remove_if(...), values.end());','#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){std::vector<int> v{1,2,3,4};v.erase(std::remove_if(v.begin(),v.end(),[](int x){return x%2==0;}),v.end());for(int x:v)std::cout<<x<<" ";}','1 3 ','remove_if không tự giảm size container.',['cpp-vector']),
item('cpp-binary-search','binary_search và lower_bound','08 · STL Algorithms','binary_search kiểm tra phần tử trong range đã sắp xếp. lower_bound trả vị trí đầu tiên không nhỏ hơn giá trị; cả hai cần range có thứ tự theo cùng comparator.','std::binary_search(begin,end,value);','#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){std::vector<int> v{1,3,5,7};auto it=std::lower_bound(v.begin(),v.end(),4);std::cout<<(it-v.begin());}','2','Vị trí 2 là nơi 4 có thể chèn trước 5.',['cpp-algorithms']),
item('cpp-comparator','Comparator','08 · STL Algorithms','Comparator định nghĩa thứ tự cho sort và các algorithm. Nó phải biểu diễn strict weak ordering: không được vừa a<b vừa b<a và phải nhất quán.','std::sort(begin,end,[](const T&a,const T&b){ return a.key < b.key; });','#include <algorithm>\n#include <iostream>\n#include <vector>\nint main(){std::vector<int> v{3,1,2};std::sort(v.begin(),v.end(),[](int a,int b){return a>b;});for(int x:v)std::cout<<x<<" ";}','3 2 1 ','Lambda comparator sắp xếp giảm dần.',['cpp-algorithms']),
item('cpp-iterators','Iterator cơ bản','08 · STL Algorithms','Iterator là đối tượng giống con trỏ, đại diện vị trí trong container. begin/end tạo range nửa mở [begin,end); end không trỏ phần tử hợp lệ và không được dereference.','for (auto it=begin; it!=end; ++it) { ... }','#include <iostream>\n#include <vector>\nint main(){std::vector<int> v{2,4,6};for(auto it=v.begin();it!=v.end();++it)std::cout<<*it<<" ";}','2 4 6 ','Iterator cho phép algorithm dùng chung nhiều container.',['cpp-vector']),
item('cpp-invalidation','Iterator invalidation','08 · STL Algorithms','Một số thao tác container làm iterator/reference cũ không còn hợp lệ. vector có thể invalidation khi reallocate; list thường giữ iterator khác khi chèn. Đọc contract của container trước khi giữ iterator lâu.','auto it=v.begin();\nv.push_back(value); // may invalidate it','#include <iostream>\n#include <vector>\nint main(){std::vector<int> v{1,2};auto it=v.begin();v.reserve(10);v.push_back(3);std::cout<<*it;}','1','reserve trước giúp tránh reallocation trong ví dụ này; không nên giữ iterator nếu chưa hiểu contract.',['cpp-vector']),
item('cpp-ranges','Ranges và views','08 · STL Algorithms','C++20 ranges cho phép viết algorithm trên range thay vì cặp iterator. View như filter hoặc transform tạo pipeline lười, không tạo container mới cho tới khi bạn yêu cầu.','std::ranges::sort(values);\nvalues | std::views::filter(pred);','#include <iostream>\n#include <ranges>\n#include <vector>\nint main(){std::vector<int> v{1,2,3,4};for(int x:v|std::views::filter([](int n){return n%2==0;}))std::cout<<x<<" ";}','2 4 ','filter view chỉ tạo giá trị khi vòng lặp yêu cầu.',['cpp-algorithms']),
item('cpp-operator-overload','Operator overloading','06 · OOP','Operator overloading cho phép kiểu tự định nghĩa dùng cú pháp tự nhiên như + hoặc ==. Overload nên giữ ý nghĩa trực quan, không tạo hành vi bất ngờ.','Type operator+(const Type& other) const;','#include <iostream>\nstruct Point{int x,y;Point operator+(const Point& o)const{return {x+o.x,y+o.y};}};\nint main(){Point a{1,2},b{3,4};Point c=a+b;std::cout<<c.x<<" "<<c.y;}','4 6','a+b gọi member operator+ và tạo Point mới.',['cpp-class']),
item('cpp-abstract','Abstract class','07 · Polymorphism','Abstract class có ít nhất một pure virtual function và không thể tạo object trực tiếp. Nó mô tả interface chung để class dẫn xuất phải cung cấp implementation.','virtual double area() const = 0;','#include <iostream>\nstruct Shape{virtual double area()const=0;virtual ~Shape()=default;};\nstruct Square:Shape{double s;double area()const override{return s*s;}};\nint main(){Square x{3};std::cout<<x.area();}','9','Shape chỉ là interface; Square mới là class cụ thể có thể tạo.',['cpp-polymorphism']),
item('cpp-interface','Interface bằng class thuần ảo','07 · Polymorphism','C++ không có từ khóa interface riêng; một class chỉ chứa pure virtual functions và virtual destructor có thể đóng vai trò interface. Client phụ thuộc abstraction thay vì class cụ thể.','struct Logger { virtual void write() = 0; virtual ~Logger() = default; };','#include <iostream>\nstruct Logger{virtual void write()=0;virtual ~Logger()=default;};\nstruct ConsoleLogger:Logger{void write()override{std::cout<<"log";}};\nint main(){ConsoleLogger l;l.write();}','log','ConsoleLogger thực hiện hợp đồng write của Logger.',['cpp-abstract']),
item('cpp-virtual-dispatch','Virtual dispatch','07 · Polymorphism','Khi gọi virtual function qua reference hoặc pointer base, C++ chọn implementation theo object thật lúc chạy. Đây là cơ chế dynamic polymorphism; gọi qua object value sẽ không có dispatch động như vậy.','baseRef.virtualMethod();','#include <iostream>\nstruct Animal{virtual void speak()const{std::cout<<"?";}virtual ~Animal()=default;};\nstruct Dog:Animal{void speak()const override{std::cout<<"Woof";}};\nint main(){Dog dog;Animal& ref=dog;ref.speak();}','Woof','Reference base vẫn dispatch tới Dog::speak.',['cpp-inheritance']),
item('cpp-copy-constructor','Copy constructor','06 · OOP','Copy constructor tạo object mới từ object cùng kiểu. Compiler có thể sinh bản sao member-wise; nếu class sở hữu tài nguyên thô, copy mặc định có thể tạo double ownership và lỗi double free.','Type(const Type& other);','#include <iostream>\nstruct Box{int value;Box(int v):value{v}{}Box(const Box& other):value{other.value}{}};\nint main(){Box a{7};Box b=a;std::cout<<b.value;}','7','b được tạo bằng constructor nhận const Box&.',['cpp-class']),
]

# Fix the intentionally complex move-constructor item with a clean compile-ready example.
items[-1] = item('cpp-move-constructor','Move constructor','06 · OOP','Move constructor chuyển tài nguyên từ temporary hoặc object sắp bị hủy thay vì sao chép. Nó thường nhận T&& và để source ở trạng thái hợp lệ nhưng không xác định giá trị.','Type(Type&& other) noexcept;','#include <iostream>\n#include <string>\n#include <utility>\nstruct Name{std::string value;Name(std::string v):value{std::move(v){}};\nint main(){Name n{"An"};std::cout<<n.value;}','An','std::move cho phép chuyển string vào member thay vì tạo thêm bản sao không cần thiết.',['cpp-copy-constructor'])

items += [
item('cpp-rule-of-zero','Rule of zero','06 · OOP','Rule of zero khuyên class không tự viết destructor, copy/move constructor hoặc assignment nếu có thể giao ownership cho RAII types như string, vector và smart pointer. Compiler-generated operations khi đó thường đúng.','class Type { std::string data; std::vector<int> values; };','#include <iostream>\n#include <string>\nstruct User{std::string name;};\nint main(){User a{"An"};User b=a;std::cout<<b.name;}','An','string tự quản lý bộ nhớ nên User không cần special member function.',['cpp-smart-pointers']),
item('cpp-object-slicing','Object slicing','07 · Polymorphism','Object slicing xảy ra khi copy object dẫn xuất vào object base by value; phần dữ liệu dẫn xuất bị cắt. Dùng reference, pointer hoặc value-semantic thiết kế phù hợp để tránh mất hành vi.','Base base = derived; // slices','#include <iostream>\nstruct Base{virtual const char* name()const{return "base";}virtual ~Base()=default;};\nstruct Child:Base{const char* name()const override{return "child";}};\nvoid print(const Base& b){std::cout<<b.name();}\nint main(){Child c;print(c);}','child','Truyền const Base& giữ object thật và cho phép virtual dispatch.',['cpp-virtual-dispatch']),
item('cpp-function-template','Function templates','09 · Templates','Function template mô tả thuật toán một lần cho nhiều kiểu. Compiler sinh specialization cần thiết khi hàm được gọi; type phải hỗ trợ các phép toán trong thân hàm.','template<class T> T maxValue(T a,T b);','#include <iostream>\ntemplate<class T>T maxValue(T a,T b){return a>b?a:b;}\nint main(){std::cout<<maxValue(3,5)<<" "<<maxValue(2.5,1.5);}','5 2.5','Một template dùng được cho int và double vì cả hai hỗ trợ >.',['cpp-functions']),
item('cpp-class-template','Class templates','09 · Templates','Class template tạo family các kiểu như Box<int> và Box<std::string>. Kiểu tham số hóa được kiểm tra tại compile time và không cần base class chung.','template<class T> class Box { T value; };','#include <iostream>\n#include <string>\ntemplate<class T>struct Box{T value;};\nint main(){Box<int>a{7};Box<std::string>b{"C++"};std::cout<<a.value<<" "<<b.value;}','7 C++','Cùng một Box lưu được nhiều kiểu khác nhau.',['cpp-function-template']),
item('cpp-non-type-template','Non-type template parameters','09 · Templates','Template parameter có thể là giá trị compile-time, chẳng hạn kích thước mảng. Điều này tạo kiểu khác nhau cho mỗi kích thước và không cần allocation động.','template<class T, std::size_t N> struct Buffer;','#include <iostream>\n#include <array>\ntemplate<class T,std::size_t N>std::size_t sizeOf(const std::array<T,N>&){return N;}\nint main(){std::array<int,4>a{};std::cout<<sizeOf(a);}','4','N được truyền như một giá trị compile-time.',['cpp-array']),
item('cpp-specialization','Template specialization','09 · Templates','Specialization cung cấp implementation riêng cho một kiểu hoặc trường hợp đặc biệt. Chỉ dùng khi hành vi thật sự khác; nếu chỉ khác dữ liệu, template tổng quát thường đủ.','template<> struct Printer<bool> { ... };','#include <iostream>\ntemplate<class T>struct Label{static const char*get(){return "value";}};\ntemplate<>struct Label<bool>{static const char*get(){return "boolean";}};\nint main(){std::cout<<Label<int>::get()<<" "<<Label<bool>::get();}','value boolean','Specialization bool chọn implementation riêng.',['cpp-class-template']),
item('cpp-variadic','Variadic templates và fold expressions','09 · Templates','Variadic template nhận số lượng tham số bất kỳ. Fold expression C++17 gọn hóa việc gộp parameter pack mà không cần đệ quy thủ công.','template<class... T> auto sum(T... values) { return (... + values); }','#include <iostream>\ntemplate<class... T>auto sum(T... values){return (...+values);}\nint main(){std::cout<<sum(1,2,3,4);}','10','Fold trái cộng toàn bộ pack theo thứ tự.',['cpp-function-template']),
item('cpp-if-constexpr','if constexpr','09 · Templates','if constexpr loại bỏ nhánh không phù hợp ngay khi biên dịch. Nó cho phép template kiểm tra đặc điểm kiểu mà không khiến compiler phân tích code không hợp lệ ở nhánh bị loại.','if constexpr (condition) { ... }','#include <iostream>\n#include <type_traits>\ntemplate<class T>void show(T value){if constexpr(std::is_integral_v<T>)std::cout<<"integer";else std::cout<<"other";}\nint main(){show(3);}','integer','Nhánh được chọn dựa trên kiểu T tại compile time.',['cpp-type-traits']),
item('cpp-concepts','Concepts và constraints','09 · Templates','Concept mô tả yêu cầu đối với template parameter bằng tên có ý nghĩa. requires giúp lỗi template gần nơi gọi hơn và ngăn nhận kiểu không hỗ trợ phép toán cần thiết.','template<class T> requires std::integral<T> T twice(T x);','#include <concepts>\n#include <iostream>\ntemplate<std::integral T>T twice(T x){return x*2;}\nint main(){std::cout<<twice(4);}','8','Concept integral giới hạn hàm cho kiểu số nguyên.',['cpp-if-constexpr']),
item('cpp-lifetime','Lifetime và dangling references','10 · Resource Safety','Lifetime là khoảng thời gian object tồn tại. Reference hoặc pointer chỉ hợp lệ trong lifetime của object; hiểu lifetime giúp tránh trả về địa chỉ local và dùng iterator đã hết hiệu lực.','Object object; // lifetime begins\n// lifetime ends at scope end','#include <iostream>\nconst int& safe(){static int value=7;return value;}\nint main(){std::cout<<safe();}','7','static object sống tới cuối chương trình nên reference còn hợp lệ.',['cpp-scope']),
item('cpp-dangling','Dangling pointer/reference','10 · Resource Safety','Dangling pointer là pointer vẫn giữ địa chỉ nhưng object đã bị hủy. Dereference nó là undefined behavior; cách phòng tránh là ownership rõ, scope phù hợp và không trả reference tới local.','int* p = nullptr;','#include <iostream>\nint main(){int value=5;int* p=&value;std::cout<<*p;}','5','p chỉ dùng trong lifetime của value.',['cpp-pointers']),
item('cpp-ownership','Ownership và borrowing','10 · Resource Safety','Ownership trả lời ai chịu trách nhiệm hủy tài nguyên; borrowing là dùng tạm qua reference/view mà không sở hữu. unique_ptr thể hiện owner, const reference thể hiện borrower chỉ đọc.','void inspect(const Resource& resource);','#include <iostream>\n#include <memory>\nvoid inspect(const int& value){std::cout<<value;}\nint main(){auto owner=std::make_unique<int>(7);inspect(*owner);}','7','owner sở hữu int; inspect chỉ mượn qua const reference.',['cpp-smart-pointers']),
item('cpp-weak-ptr','std::weak_ptr và cycle','10 · Resource Safety','weak_ptr quan sát object do shared_ptr quản lý nhưng không tăng reference count. Dùng lock() để lấy shared_ptr tạm; weak_ptr giúp phá cycle giữa các object liên kết.','std::weak_ptr<T> observer;\nif(auto p=observer.lock()) { ... }','#include <iostream>\n#include <memory>\nint main(){auto owner=std::make_shared<int>(7);std::weak_ptr<int> view=owner;if(auto p=view.lock())std::cout<<*p;}','7','lock trả shared_ptr nếu object vẫn còn sống.',['cpp-smart-pointers']),
item('cpp-exception-safety','Exception safety guarantees','10 · Resource Safety','Exception safety mô tả trạng thái chương trình khi lỗi xảy ra: no-throw, strong guarantee (không đổi state nếu thất bại) và basic guarantee (invariant vẫn đúng). RAII giúp rollback resource tự động.','try { operation(); } catch (...) { /* state remains valid */ }','#include <iostream>\n#include <vector>\nvoid add(std::vector<int>& v,int x){std::vector<int> copy=v;copy.push_back(x);v.swap(copy);}\nint main(){std::vector<int>v{1};add(v,2);std::cout<<v.size();}','2','Copy-then-swap chỉ thay state sau khi thao tác có thể ném hoàn thành.',['cpp-exceptions']),
item('cpp-custom-raii','Tự tạo wrapper RAII','10 · Resource Safety','Wrapper RAII nhận resource trong constructor và giải phóng trong destructor. Class sở hữu tài nguyên nên cấm copy hoặc định nghĩa move rõ; ưu tiên dùng wrapper thư viện chuẩn khi có.','ResourceGuard() { acquire(); }\n~ResourceGuard() { release(); }','#include <iostream>\nstruct Guard{const char*name;explicit Guard(const char*n):name{n}{std::cout<<"open ";}~Guard(){std::cout<<"close";}};\nint main(){Guard g{"file"};}','open close','Destructor chạy khi g ra khỏi scope, kể cả khi return sớm.',['cpp-rule-of-zero']),
item('cpp-ub-sanitizer','Undefined behavior và sanitizer','10 · Resource Safety','Undefined behavior là chương trình vi phạm điều kiện chuẩn, khiến compiler không phải đảm bảo kết quả. AddressSanitizer và UndefinedBehaviorSanitizer giúp phát hiện nhiều lỗi khi test; compiler warnings vẫn cần thiết.','g++ -fsanitize=address,undefined -g main.cpp','#include <iostream>\nint main(){int a[2]{1,2};std::cout<<a[0];}','1','Lệnh sanitizer là công cụ build/debug; code mẫu truy cập trong giới hạn.',['cpp-debugging']),
item('cpp-structured-bindings','Structured bindings','11 · Modern C++','Structured binding tách các thành phần của pair, tuple, array hoặc object có binding phù hợp thành các tên cục bộ. Nó làm vòng lặp map và hàm trả nhiều giá trị dễ đọc hơn.','auto [name, score] = entry;','#include <iostream>\n#include <utility>\nint main(){auto [name,score]=std::pair{"An",9};std::cout<<name<<" "<<score;}','An 9','Hai tên được bind vào first và second của pair.',['cpp-tuple']),
item('cpp-decltype','decltype','11 · Modern C++','decltype lấy kiểu của một biểu thức mà không chạy biểu thức đó. Nó hữu ích trong generic code, trailing return type và giữ chính xác reference/constness.','decltype(expression) name;','#include <iostream>\nint main(){int n=7;decltype(n) copy=3;std::cout<<copy;}','3','decltype(n) là int vì n là int.',['cpp-auto']),
item('cpp-move','std::move','11 · Modern C++','std::move không tự di chuyển dữ liệu; nó cast expression thành rvalue để overload move có thể được chọn. Sau khi move, object nguồn vẫn hợp lệ nhưng giá trị không nên đoán.','target = std::move(source);','#include <iostream>\n#include <string>\n#include <utility>\nint main(){std::string source="hello";std::string target=std::move(source);std::cout<<target;}','hello','Move constructor nhận quyền sử dụng buffer của source khi có thể.',['cpp-move-constructor']),
item('cpp-consteval','consteval','11 · Modern C++','consteval tạo immediate function: mọi lời gọi phải được tính tại compile time. Nó mạnh hơn constexpr khi API bắt buộc kết quả không được tính lúc runtime.','consteval int value() { return 42; }','#include <iostream>\nconsteval int answer(){return 42;}\nint main(){constexpr int n=answer();std::cout<<n;}','42','answer được gọi trong ngữ cảnh compile-time.',['cpp-const']),
item('cpp-filesystem','std::filesystem','11 · Modern C++','filesystem cung cấp path và thao tác file/thư mục portable hơn việc nối chuỗi thủ công. Có thể kiểm tra tồn tại, lấy extension và duyệt directory; luôn xử lý permission/error.','std::filesystem::path path{"file.txt"};','#include <filesystem>\n#include <iostream>\nint main(){std::filesystem::path p{"notes.txt"};std::cout<<p.extension().string();}','.txt','path tách phần extension theo quy tắc filesystem.',['cpp-files']),
item('cpp-chrono','std::chrono','11 · Modern C++','chrono biểu diễn duration, time_point và clock với kiểu an toàn. Dùng steady_clock để đo khoảng thời gian vì nó không lùi theo thay đổi đồng hồ hệ thống.','auto start=std::chrono::steady_clock::now();','#include <chrono>\n#include <iostream>\nint main(){auto start=std::chrono::steady_clock::now();auto end=start+std::chrono::milliseconds(25);std::cout<<std::chrono::duration_cast<std::chrono::milliseconds>(end-start).count();}','25','duration_cast chuyển duration về đơn vị milliseconds.',['cpp-functions']),
item('cpp-regex','std::regex','11 · Modern C++','regex biểu diễn mẫu tìm kiếm và validation text. Nó tiện cho mẫu vừa phải nhưng có thể tốn chi phí; input không tin cậy cần giới hạn và pattern được kiểm thử.','std::regex pattern{"..."};\nstd::regex_match(text,pattern);','#include <iostream>\n#include <regex>\nint main(){std::regex p{"[0-9]+"};std::cout<<std::regex_match(std::string{"2026"},p);}','1','Chuỗi 2026 khớp pattern chỉ gồm chữ số.',['cpp-string']),
item('cpp-three-way','Three-way comparison <=>','11 · Modern C++','Toán tử spaceship <=> tạo kết quả so sánh thứ tự, giúp sinh các phép so sánh liên quan. Nó cần header compare và một kiểu category phù hợp như strong_ordering.','auto result = left <=> right;','#include <compare>\n#include <iostream>\nint main(){int a=2,b=3;auto result=a<=>b;std::cout<<(result<0);}','1','result<0 nghĩa là a đứng trước b.',['cpp-comparison']),
item('cpp-expected','std::expected (C++23 overview)','11 · Modern C++','std::expected<T,E> là công cụ C++23 để trả về kết quả hoặc lỗi mà không dùng exception cho mọi trường hợp. Khi compiler chỉ bật C++20, có thể dùng pair/variant/optional hoặc result type riêng làm fallback.','std::expected<T,E> parse(text);','#include <iostream>\n#include <optional>\nstd::optional<int> parsePositive(int n){return n>=0?std::optional<int>{n}:std::nullopt;}\nint main(){std::cout<<parsePositive(4).value_or(0);}','4','Ví dụ dùng optional làm fallback C++20 cho API expected-like.',['cpp-optional']),
item('cpp-thread','Thread, future và async','11 · Modern C++','C++ cung cấp thread, mutex, future và async cho tác vụ đồng thời. Chia sẻ dữ liệu cần synchronization; future giúp nhận kết quả và exception từ tác vụ bất đồng bộ.','#include <future>\nauto result=std::async(std::launch::async, task);','#include <future>\n#include <iostream>\nint main(){auto future=std::async(std::launch::async,[]{return 6*7;});std::cout<<future.get();}','42','get chờ task hoàn thành và lấy kết quả.',['cpp-functions']),
item('cpp-span-modern','std::span trong API hiện đại','11 · Modern C++','span là cách hiện đại để nhận một range liên tiếp không sở hữu. Dùng nó thay cặp pointer+length khi API cần đọc nhiều loại buffer mà không copy.','void process(std::span<const T> values);','#include <iostream>\n#include <span>\nvoid process(std::span<const int> values){std::cout<<values.front()<<" "<<values.back();}\nint main(){std::array<int,3>a{1,2,3};process(a);}','1 3','API nhận std::array qua span mà không cần overload riêng.',['cpp-span']),
]

# Remove accidental duplicate ids if this script is re-run.
existing = set()
for token in s.split("E('")[1:]:
    existing.add(token.split("'",1)[0])
new_items = [x for x in items if x['id'] not in existing]

lines = ['\n  // Additional C++ curriculum: STL, OOP, templates, memory safety and modern C++.']
for x in new_items:
    args = [x['id'], x['title'], x['chapter'], x['concept'], x['syntax'], x['code'], x['output'], x['explanation'], x['prerequisites']]
    lines.append('  E(' + ','.join(json.dumps(a, ensure_ascii=False) for a in args) + '),')
block = '\n'.join(lines).rstrip(',') + '\n'
s = s.replace(marker, block + '  ' + marker, 1)
p.write_text(s, encoding='utf-8')
print('added', len(new_items), 'lessons')
