(function(){
  const S = (id,topic,title,difficulty,minutes,description,starter,tests,hints,solution,explanation,tags) => ({id,slug:id.replace(/^c-ex-/,'').replace(/[^a-z0-9-]/g,'-'),topic,title,difficulty,estimatedTime:minutes,description,starterCode:starter,testCases:tests,hints,solution,explanation,tags});
  const e=[];
  const add=(topic,items)=>items.forEach(x=>e.push(S('c-ex-'+String(e.length+1).padStart(3,'0'),topic,...x)));
  add('C Basics',[
    ['Hello World','easy',5,'In dòng chữ Hello, World! ra màn hình.','// Viết chương trình của bạn ở đây\n', [{input:'',expected:'Hello, World!'}],['Dùng thư viện stdio.h.','Hàm xuất màn hình là printf().','Chuỗi cần đặt trong dấu ngoặc kép.'],'#include <stdio.h>\nint main(void) { printf("Hello, World!\\n"); return 0; }','main là điểm bắt đầu; printf in chuỗi.',['printf','main']],
    ['Print Your Name','easy',5,'Nhập tên? Không cần input: hãy in tên của bạn và một dòng chào.','#include <stdio.h>\nint main(void) {\n    // In ten va loi chao\n    return 0;\n}',[{input:'',expected:'An\nXin chao An'}],['Dùng hai lần printf().','Mỗi output ở một dòng.','Thay An bằng tên bạn.'],'#include <stdio.h>\nint main(void) { printf("An\\nXin chao An\\n"); return 0; }','Hai lệnh printf hoặc một chuỗi có newline đều được.',['printf','strings']],
    ['Sum of Two Numbers','easy',7,'Đọc hai số nguyên a và b, in tổng của chúng.','#include <stdio.h>\nint main(void) {\n    int a, b;\n    scanf("%d %d", &a, &b);\n    // In tong\n    return 0;\n}',[{input:'5 7',expected:'12'},{input:'-5 10',expected:'5'},{input:'0 0',expected:'0'}],['Khai báo hai int.','Đọc bằng scanf("%d %d", &a, &b).','In a + b.'],'#include <stdio.h>\nint main(void) { int a,b; scanf("%d %d",&a,&b); printf("%d\\n",a+b); return 0; }','Toán tử + cộng hai số nguyên.',['scanf','arithmetic']],
    ['Rectangle Area','easy',7,'Đọc chiều dài và chiều rộng là số thực, in diện tích với 2 chữ số thập phân.','#include <stdio.h>\nint main(void) {\n    double length, width;\n    scanf("%lf %lf", &length, &width);\n    return 0;\n}',[{input:'4 2.5',expected:'10.00'},{input:'3 3',expected:'9.00'}],['Diện tích = dài * rộng.','Dùng double và %lf khi scanf.','In bằng %.2f.'],'#include <stdio.h>\nint main(void) { double l,w; scanf("%lf %lf",&l,&w); printf("%.2f\\n",l*w); return 0; }','Giữ số thực để không mất phần thập phân.',['double','printf']],
    ['Celsius to Fahrenheit','easy',7,'Đọc nhiệt độ Celsius, đổi sang Fahrenheit theo công thức F = C * 9 / 5 + 32.','#include <stdio.h>\nint main(void) {\n    double c;\n    scanf("%lf", &c);\n    return 0;\n}',[{input:'0',expected:'32.00'},{input:'100',expected:'212.00'},{input:'-40',expected:'-40.00'}],['Dùng công thức đúng thứ tự.','Số 9 và 5 nên được tính trong double.','In 2 chữ số.'],'#include <stdio.h>\nint main(void) { double c; scanf("%lf",&c); printf("%.2f\\n",c*9.0/5.0+32.0); return 0; }','Dùng hằng số thực để phép chia không bị chia nguyên.',['formula','double']]
  ]);
  add('Variables & Data Types',[
    ['Integer Variable','easy',5,'Đọc một số nguyên và in lại theo mẫu Value: n.','#include <stdio.h>\nint main(void) { int n; scanf("%d", &n); return 0; }',[{input:'42',expected:'Value: 42'}],['Giữ dữ liệu trong int.','Chuỗi mẫu đặt trước %d.','In n sau dấu phẩy.'],'#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); printf("Value: %d\\n",n); return 0; }','int lưu số nguyên.',['int','format']],
    ['Floating Point Calculation','easy',8,'Đọc hai số thực và in trung bình cộng với 2 chữ số thập phân.','#include <stdio.h>\nint main(void) { double a,b; scanf("%lf %lf",&a,&b); return 0; }',[{input:'8 10',expected:'9.00'},{input:'1.5 2.5',expected:'2.00'}],['Cộng rồi chia cho 2.0.','Dùng %lf cho scanf.','Dùng %.2f khi in.'],'#include <stdio.h>\nint main(void) { double a,b; scanf("%lf %lf",&a,&b); printf("%.2f\\n",(a+b)/2.0); return 0; }','double giữ phần thập phân.',['double','average']],
    ['Character Input','easy',6,'Đọc một ký tự và in mã ký tự của nó theo mẫu Code: n.','#include <stdio.h>\nint main(void) { char c; scanf(" %c", &c); return 0; }',[{input:'A',expected:'Code: 65'},{input:'z',expected:'Code: 122'}],['Dùng %c.','Khoảng trắng trước %c bỏ newline còn lại.','In char bằng %d để xem mã.'],'#include <stdio.h>\nint main(void) { char c; scanf(" %c",&c); printf("Code: %d\\n",c); return 0; }','char có thể được in như mã số nguyên.',['char','scanf']],
    ['Calculate Average','medium',10,'Đọc ba điểm số thực, in điểm trung bình với 1 chữ số thập phân.','#include <stdio.h>\nint main(void) { double a,b,c; scanf("%lf %lf %lf",&a,&b,&c); return 0; }',[{input:'8 7 9',expected:'8.0'},{input:'5.5 6.5 7.5',expected:'6.5'}],['Tổng ba số rồi chia 3.0.','Không dùng chia nguyên.','Định dạng %.1f.'],'#include <stdio.h>\nint main(void) { double a,b,c; scanf("%lf %lf %lf",&a,&b,&c); printf("%.1f\\n",(a+b+c)/3.0); return 0; }','Chia cho 3.0 bảo toàn số thực.',['average','double']],
    ['Simple Calculator','medium',12,'Đọc a, một toán tử (+ - * /) và b; in kết quả. Phép chia dùng số thực.','#include <stdio.h>\nint main(void) { double a,b; char op; scanf("%lf %c %lf",&a,&op,&b); return 0; }',[{input:'8 + 2',expected:'10.00'},{input:'8 / 2',expected:'4.00'},{input:'7 * 3',expected:'21.00'}],['Đọc op bằng %c.','Dùng switch hoặc if.','Kiểm tra b khác 0 khi chia.'],'#include <stdio.h>\nint main(void) { double a,b,r=0; char op; scanf("%lf %c %lf",&a,&op,&b); switch(op){case \' + \' : r=a+b; break; case \'-\': r=a-b; break; case \'*\': r=a*b; break; case \'/\': if(b!=0) r=a/b; break;} printf("%.2f\\n",r); return 0; }','Toán tử được chọn dựa vào ký tự op.',['switch','calculator']]
  ]);
  add('Conditions',[
    ['Positive or Negative','easy',5,'Đọc một số nguyên và in Positive, Negative hoặc Zero.','#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'8',expected:'Positive'},{input:'-2',expected:'Negative'},{input:'0',expected:'Zero'}],['So sánh n với 0.','Dùng ba nhánh.','In đúng chữ hoa đầu câu.'],'#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); if(n>0) puts("Positive"); else if(n<0) puts("Negative"); else puts("Zero"); return 0; }','if/else if/else phân loại ba trường hợp.',['if','comparison']],
    ['Even or Odd','easy',5,'Đọc n và in Even nếu n chia hết cho 2, ngược lại in Odd.','#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'8',expected:'Even'},{input:'7',expected:'Odd'},{input:'-3',expected:'Odd'}],['Dùng toán tử %.','Phần dư bằng 0 nghĩa là chẵn.','Số âm vẫn dùng được.'],'#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); puts(n%2==0?"Even":"Odd"); return 0; }','n % 2 kiểm tra phần dư.',['if','modulo']],
    ['Largest of Two Numbers','easy',6,'Đọc hai số nguyên và in số lớn hơn; nếu bằng nhau vẫn in giá trị đó.','#include <stdio.h>\nint main(void) { int a,b; scanf("%d %d",&a,&b); return 0; }',[{input:'5 9',expected:'9'},{input:'10 2',expected:'10'},{input:'4 4',expected:'4'}],['So sánh a > b.','Chọn a hoặc b.','In một số.'],'#include <stdio.h>\nint main(void) { int a,b; scanf("%d %d",&a,&b); printf("%d\\n",a>b?a:b); return 0; }','Toán tử ba ngôi chọn một trong hai giá trị.',['if','ternary']],
    ['Largest of Three Numbers','medium',8,'Đọc ba số nguyên và in số lớn nhất.','#include <stdio.h>\nint main(void) { int a,b,c; scanf("%d %d %d",&a,&b,&c); return 0; }',[{input:'10 25 15',expected:'25'},{input:'9 9 2',expected:'9'}],['Khởi tạo max bằng a.','So sánh lần lượt b và c.','Không cần sort mảng.'],'#include <stdio.h>\nint main(void) { int a,b,c,max; scanf("%d %d %d",&a,&b,&c); max=a; if(b>max)max=b; if(c>max)max=c; printf("%d\\n",max); return 0; }','Giữ giá trị lớn nhất hiện tại sau từng lần so sánh.',['if','max']],
    ['Grade Classification','medium',10,'Đọc điểm 0..100 và in A (>=90), B (>=80), C (>=70), D (>=50), F còn lại.','#include <stdio.h>\nint main(void) { int score; scanf("%d",&score); return 0; }',[{input:'95',expected:'A'},{input:'82',expected:'B'},{input:'49',expected:'F'}],['Kiểm tra ngưỡng cao trước.','Dùng else if.','Bài yêu cầu điểm hợp lệ.'],'#include <stdio.h>\nint main(void) { int s; scanf("%d",&s); if(s>=90)puts("A"); else if(s>=80)puts("B"); else if(s>=70)puts("C"); else if(s>=50)puts("D"); else puts("F"); return 0; }','Thứ tự điều kiện từ cao xuống thấp tránh nhánh rộng chặn nhánh hẹp.',['if','grading']]
  ]);
  add('Loops',[
    ['Print 1 to N','easy',6,'Đọc n và in các số từ 1 đến n trên một dòng, cách nhau bằng dấu cách.','#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'5',expected:'1 2 3 4 5'},{input:'1',expected:'1'}],['Dùng for bắt đầu từ 1.','Dừng khi i <= n.','In dấu cách giữa các số.'],'#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); for(int i=1;i<=n;i++){ if(i>1) putchar(\' \'); printf("%d",i); } putchar(\'\\n\'); return 0; }','for quản lý biến đếm và điều kiện dừng.',['for','counter']],
    ['Sum 1 to N','easy',7,'Đọc n và in tổng 1 + 2 + ... + n.','#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'5',expected:'15'},{input:'1',expected:'1'}],['Khởi tạo sum=0.','Cộng i trong vòng lặp.','Dùng long long nếu n lớn.'],'#include <stdio.h>\nint main(void) { int n; long long sum=0; scanf("%d",&n); for(int i=1;i<=n;i++)sum+=i; printf("%lld\\n",sum); return 0; }','Accumulator giữ tổng sau mỗi lượt.',['for','sum']],
    ['Multiplication Table','easy',8,'Đọc n và in bảng nhân n từ 1 đến 10, mỗi dòng dạng n x i = result.','#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'3',expected:'3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15\n3 x 6 = 18\n3 x 7 = 21\n3 x 8 = 24\n3 x 9 = 27\n3 x 10 = 30'}],['Loop i từ 1 đến 10.','In n, i và n*i.','Dùng newline mỗi dòng.'],'#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); for(int i=1;i<=10;i++) printf("%d x %d = %d\\n",n,i,n*i); return 0; }','Một vòng lặp tạo mười dòng có cùng khuôn.',['for','printf']],
    ['Factorial','medium',8,'Đọc n không âm và in n! = 1 * 2 * ... * n.','#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'5',expected:'120'},{input:'0',expected:'1'}],['Khởi tạo result=1.','Nhân từ 2 đến n.','0! bằng 1.'],'#include <stdio.h>\nint main(void) { int n; unsigned long long r=1; scanf("%d",&n); for(int i=2;i<=n;i++)r*=i; printf("%llu\\n",r); return 0; }','Factorial là phép nhân tích lũy; trường hợp 0 cần giữ result=1.',['for','factorial']],
    ['Fibonacci Sequence','hard',15,'Đọc n và in n số Fibonacci đầu tiên, bắt đầu 0 1.','#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'6',expected:'0 1 1 2 3 5'},{input:'1',expected:'0'}],['Giữ hai số trước.','In a rồi cập nhật a=b, b=a+b.','Xử lý n=0 và n=1.'],'#include <stdio.h>\nint main(void) { int n; long long a=0,b=1; scanf("%d",&n); for(int i=0;i<n;i++){ if(i)putchar(\' \'); printf("%lld",a); long long next=a+b; a=b; b=next; } putchar(\'\\n\'); return 0; }','Chỉ cần hai giá trị trước, không cần mảng.',['for','sequence']]
  ]);
  add('Arrays',[
    ['Input Array','easy',8,'Đọc n rồi đọc n số nguyên, sau đó in lại theo thứ tự ban đầu.','#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'4\n2 4 6 8',expected:'2 4 6 8'}],['Tạo mảng đủ kích thước.','Lưu từng phần tử bằng for.','Duyệt lại để in.'],'#include <stdio.h>\nint main(void) { int n,a[100]; scanf("%d",&n); for(int i=0;i<n;i++)scanf("%d",&a[i]); for(int i=0;i<n;i++){if(i)putchar(\' \');printf("%d",a[i]);} return 0; }','Mảng cho phép giữ nhiều int cùng kiểu.',['array','input']],
    ['Sum Array Elements','easy',8,'Đọc n phần tử và in tổng các phần tử.','#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'4\n1 2 3 4',expected:'10'},{input:'3\n-2 5 1',expected:'4'}],['sum bắt đầu 0.','Cộng a[i] trong vòng lặp.','Dùng long long nếu cần.'],'#include <stdio.h>\nint main(void) { int n,a[100]; long long sum=0; scanf("%d",&n); for(int i=0;i<n;i++){scanf("%d",&a[i]);sum+=a[i];} printf("%lld\\n",sum); return 0; }','Duyệt từng phần tử một lần.',['array','sum']],
    ['Find Maximum','easy',8,'Đọc mảng và in phần tử lớn nhất.','#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'5\n4 9 2 7 1',expected:'9'},{input:'3\n-4 -2 -8',expected:'-2'}],['Khởi tạo max bằng phần tử đầu.','So sánh từ phần tử thứ hai.','Không khởi tạo max=0 vì mảng có thể toàn số âm.'],'#include <stdio.h>\nint main(void) { int n,a[100]; scanf("%d",&n); for(int i=0;i<n;i++)scanf("%d",&a[i]); int max=a[0]; for(int i=1;i<n;i++)if(a[i]>max)max=a[i]; printf("%d\\n",max); return 0; }','Giữ invariant max là phần tử lớn nhất đã duyệt.',['array','max']],
    ['Find Minimum','easy',8,'Đọc mảng và in phần tử nhỏ nhất.','#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'4\n8 3 6 1',expected:'1'},{input:'2\n-1 -9',expected:'-9'}],['Khởi tạo min bằng a[0].','Cập nhật khi a[i] nhỏ hơn.','Xử lý số âm.'],'#include <stdio.h>\nint main(void) { int n,a[100]; scanf("%d",&n); for(int i=0;i<n;i++)scanf("%d",&a[i]); int min=a[0]; for(int i=1;i<n;i++)if(a[i]<min)min=a[i]; printf("%d\\n",min); return 0; }','Không dùng min=0 nếu miền dữ liệu có số âm.',['array','min']],
    ['Reverse Array','medium',10,'Đọc mảng và in các phần tử theo thứ tự ngược lại.','#include <stdio.h>\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'5\n1 2 3 4 5',expected:'5 4 3 2 1'},{input:'3\n7 8 9',expected:'9 8 7'}],['Duyệt index từ n-1 về 0.','Không cần mảng thứ hai.','Quản lý dấu cách.'],'#include <stdio.h>\nint main(void) { int n,a[100]; scanf("%d",&n); for(int i=0;i<n;i++)scanf("%d",&a[i]); for(int i=n-1;i>=0;i--){if(i<n-1)putchar(\' \');printf("%d",a[i]);} return 0; }','Đọc theo chiều ngược là đủ nếu chỉ cần output.',['array','reverse']]
  ]);
  add('Strings',[
    ['String Length','easy',8,'Đọc một dòng text và in số ký tự trước newline.','#include <stdio.h>\nint main(void) { char s[200]; fgets(s,sizeof s,stdin); return 0; }',[{input:'hello',expected:'5'},{input:'C language',expected:'10'}],['Dùng strlen trong string.h.','fgets có thể giữ newline.','Trừ newline khỏi độ dài nếu có.'],'#include <stdio.h>\n#include <string.h>\nint main(void) { char s[200]; fgets(s,sizeof s,stdin); s[strcspn(s,"\\n")]=0; printf("%zu\\n",strlen(s)); return 0; }','strcspn tìm vị trí newline để loại khỏi chuỗi.',['string.h','strlen']],
    ['Count Characters','easy',8,'Đọc một dòng và đếm số chữ cái alphabet trong đó.','#include <stdio.h>\nint main(void) { char s[200]; fgets(s,sizeof s,stdin); return 0; }',[{input:'C 101!',expected:'1'},{input:'Hello World',expected:'10'}],['Duyệt tới \\0.','Dùng isalpha trong ctype.h.','Không tính khoảng trắng và số.'],'#include <stdio.h>\n#include <string.h>\n#include <ctype.h>\nint main(void) { char s[200]; fgets(s,sizeof s,stdin); int count=0; for(int i=0;s[i];i++) if(isalpha((unsigned char)s[i])) count++; printf("%d\\n",count); return 0; }','isalpha kiểm tra ký tự chữ theo locale hiện tại.',['string','ctype']],
    ['Count Vowels','medium',10,'Đếm nguyên âm a, e, i, o, u không phân biệt hoa thường.','#include <stdio.h>\nint main(void) { char s[200]; fgets(s,sizeof s,stdin); return 0; }',[{input:'Education',expected:'5'},{input:'rhythm',expected:'0'}],['Chuyển ký tự về lowercase hoặc so sánh cả hai dạng.','Chỉ đếm năm nguyên âm.','Duyệt tới null.'],'#include <stdio.h>\n#include <ctype.h>\nint main(void) { char s[200]; fgets(s,sizeof s,stdin); int count=0; for(int i=0;s[i];i++){char c=(char)tolower((unsigned char)s[i]); if(c==\'a\'||c==\'e\'||c==\'i\'||c==\'o\'||c==\'u\')count++;} printf("%d\\n",count); return 0; }','tolower giúp xử lý hoa thường nhất quán.',['string','loop']],
    ['Reverse String','medium',10,'Đọc một dòng text và in chuỗi theo thứ tự ngược lại.','#include <stdio.h>\nint main(void) { char s[200]; fgets(s,sizeof s,stdin); return 0; }',[{input:'hello',expected:'olleh'},{input:'C code',expected:'edoc C'}],['Loại newline trước.','Tìm length.','Duyệt từ length-1 về 0.'],'#include <stdio.h>\n#include <string.h>\nint main(void) { char s[200]; fgets(s,sizeof s,stdin); s[strcspn(s,"\\n")]=0; size_t n=strlen(s); for(size_t i=n;i>0;i--)putchar(s[i-1]); putchar(\'\\n\'); return 0; }','Duyệt lùi không cần tạo chuỗi mới.',['string','reverse']],
    ['Palindrome String','hard',15,'Kiểm tra chuỗi có đọc giống nhau từ hai đầu hay không, bỏ qua khoảng trắng và không phân biệt hoa thường.','#include <stdio.h>\nint main(void) { char s[200]; fgets(s,sizeof s,stdin); return 0; }',[{input:'Never odd or even',expected:'Palindrome'},{input:'hello',expected:'Not Palindrome'}],['Dùng hai index trái/phải.','Bỏ qua whitespace.','So sánh lowercase.'],'#include <stdio.h>\n#include <ctype.h>\n#include <string.h>\nint main(void) { char s[200]; fgets(s,sizeof s,stdin); int l=0,r=(int)strlen(s)-1,ok=1; while(l<r){while(l<r&&!isalnum((unsigned char)s[l]))l++;while(l<r&&!isalnum((unsigned char)s[r]))r--; if(tolower((unsigned char)s[l])!=tolower((unsigned char)s[r])){ok=0;break;}l++;r--;} puts(ok?"Palindrome":"Not Palindrome"); return 0; }','Hai con trỏ so sánh các ký tự có ý nghĩa từ hai đầu.',['string','two-pointers']]
  ]);
  add('Functions',[
    ['Simple Function','easy',6,'Tạo hàm greet() in Hello from function, sau đó gọi từ main.','#include <stdio.h>\nvoid greet(void) { /* code */ }\nint main(void) { return 0; }',[{input:'',expected:'Hello from function'}],['Hàm không nhận tham số.','Dùng puts hoặc printf.','Gọi greet trong main.'],'#include <stdio.h>\nvoid greet(void){puts("Hello from function");}\nint main(void){greet();return 0;}','Hàm gom một nhiệm vụ có tên.',['function','void']],
    ['Function Parameters','easy',7,'Viết hàm printSquare(int n) và in bình phương của n.','#include <stdio.h>\nvoid printSquare(int n) { /* code */ }\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'4',expected:'16'},{input:'-3',expected:'9'}],['Tham số là n.','Bình phương là n*n.','Gọi hàm sau scanf.'],'#include <stdio.h>\nvoid printSquare(int n){printf("%d\\n",n*n);}\nint main(void){int n;scanf("%d",&n);printSquare(n);return 0;}','Tham số nhận bản sao giá trị khi gọi hàm.',['function','parameter']],
    ['Return Value','easy',7,'Viết hàm max2(a,b) trả về số lớn hơn và in kết quả.','#include <stdio.h>\nint max2(int a,int b) { return 0; }\nint main(void) { int a,b; scanf("%d %d",&a,&b); return 0; }',[{input:'5 9',expected:'9'},{input:'8 2',expected:'8'}],['Kiểu trả về là int.','Dùng if hoặc toán tử ?.','In giá trị hàm trả về.'],'#include <stdio.h>\nint max2(int a,int b){return a>b?a:b;}\nint main(void){int a,b;scanf("%d %d",&a,&b);printf("%d\\n",max2(a,b));return 0;}','return gửi kết quả về caller.',['function','return']],
    ['Maximum Function','medium',9,'Viết hàm maxArray(a,n) trả về phần tử lớn nhất của mảng.','#include <stdio.h>\nint maxArray(const int a[],int n) { return 0; }\nint main(void) { int n,a[100]; scanf("%d",&n); return 0; }',[{input:'4\n2 9 3 7',expected:'9'},{input:'3\n-4 -2 -8',expected:'-2'}],['Truyền thêm n vì mảng không tự biết length.','Khởi tạo max=a[0].','Duyệt từ index 1.'],'#include <stdio.h>\nint maxArray(const int a[],int n){int m=a[0];for(int i=1;i<n;i++)if(a[i]>m)m=a[i];return m;}\nint main(void){int n,a[100];scanf("%d",&n);for(int i=0;i<n;i++)scanf("%d",&a[i]);printf("%d\\n",maxArray(a,n));return 0;}','Mảng truyền vào hàm suy biến thành pointer nên cần n.',['array','function']],
    ['Prime Number Function','hard',12,'Viết hàm isPrime(n) trả 1 nếu n là số nguyên tố, 0 nếu không.','#include <stdio.h>\nint isPrime(int n) { return 0; }\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'2',expected:'Prime'},{input:'17',expected:'Prime'},{input:'21',expected:'Not Prime'},{input:'1',expected:'Not Prime'}],['Số <2 không nguyên tố.','Chỉ cần thử i*i <= n.','Dừng sớm khi chia hết.'],'#include <stdio.h>\nint isPrime(int n){if(n<2)return 0;for(int i=2;i<=n/i;i++)if(n%i==0)return 0;return 1;}\nint main(void){int n;scanf("%d",&n);puts(isPrime(n)?"Prime":"Not Prime");return 0;}','Kiểm tra tới căn bậc hai giảm số phép thử.',['function','prime']]
  ]);
  add('Pointers',[
    ['Pointer Basics','easy',7,'Đọc số nguyên, dùng pointer để thay đổi nó thành gấp đôi rồi in giá trị.','#include <stdio.h>\nint main(void) { int value; scanf("%d",&value); int *p=&value; return 0; }',[{input:'6',expected:'12'},{input:'-4',expected:'-8'}],['p giữ &value.','Gán *p = *p * 2.','In value hoặc *p.'],'#include <stdio.h>\nint main(void){int value;scanf("%d",&value);int *p=&value;*p*=2;printf("%d\\n",value);return 0;}','Dereference pointer cho phép sửa object gốc.',['pointer','dereference']],
    ['Address of Variable','easy',6,'Đọc int và in giá trị cùng địa chỉ của nó theo hai dòng. Địa chỉ có thể khác mỗi lần chạy.','#include <stdio.h>\nint main(void) { int value; scanf("%d",&value); return 0; }',[{input:'42',expected:'Value: 42\nAddress: (address)'}],['Dùng &value.','In địa chỉ bằng %p.','Địa chỉ không cần khớp mẫu cố định.'],'#include <stdio.h>\nint main(void){int value;scanf("%d",&value);printf("Value: %d\\nAddress: %p\\n",value,(void*)&value);return 0;}','%p là định dạng dành cho pointer.',['pointer','memory']],
    ['Modify with Pointer','easy',8,'Viết hàm addTen(int *p) cộng 10 vào biến gốc.','#include <stdio.h>\nvoid addTen(int *p) { /* code */ }\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'5',expected:'15'},{input:'-2',expected:'8'}],['Hàm nhận int*.','Kiểm tra p khác NULL nếu cần.','Dùng (*p)+=10.'],'#include <stdio.h>\nvoid addTen(int *p){*p+=10;}\nint main(void){int n;scanf("%d",&n);addTen(&n);printf("%d\\n",n);return 0;}','Truyền địa chỉ giúp hàm thay đổi caller-owned value.',['pointer','function']],
    ['Swap with Pointers','medium',10,'Viết hàm swap(int *a,int *b) đổi chỗ hai số nguyên.','#include <stdio.h>\nvoid swap(int *a,int *b) { /* code */ }\nint main(void) { int a,b; scanf("%d %d",&a,&b); return 0; }',[{input:'3 8',expected:'8 3'},{input:'-1 4',expected:'4 -1'}],['Cần biến tạm.','Đổi *a và *b.','Truyền &a, &b.'],'#include <stdio.h>\nvoid swap(int *a,int *b){int t=*a;*a=*b;*b=t;}\nint main(void){int a,b;scanf("%d %d",&a,&b);swap(&a,&b);printf("%d %d\\n",a,b);return 0;}','Pointer là cách trả nhiều thay đổi ra caller.',['pointer','swap']],
    ['Pointer and Array','hard',12,'Viết hàm sum(const int *begin, const int *end) tính tổng các phần tử trong [begin,end).','#include <stdio.h>\nlong long sum(const int *begin,const int *end) { return 0; }\nint main(void) { int n,a[100]; scanf("%d",&n); return 0; }',[{input:'4\n1 2 3 4',expected:'10'},{input:'3\n-2 5 1',expected:'4'}],['Dừng khi begin == end.','Cộng *begin rồi tăng begin.','Gọi sum(a,a+n).'],'#include <stdio.h>\nlong long sum(const int *begin,const int *end){long long s=0;while(begin!=end)s+=*begin++;return s;}\nint main(void){int n,a[100];scanf("%d",&n);for(int i=0;i<n;i++)scanf("%d",&a[i]);printf("%lld\\n",sum(a,a+n));return 0;}','Pointer range biểu diễn [begin,end) rõ hơn chỉ truyền một pointer.',['pointer','array']]
  ]);
  add('Structures',[
    ['Create a Struct','easy',8,'Tạo struct Point gồm x,y; đọc và in tọa độ theo mẫu (x, y).','#include <stdio.h>\nstruct Point { int x; int y; };\nint main(void) { struct Point p; return 0; }',[{input:'2 3',expected:'(2, 3)'},{input:'-1 5',expected:'(-1, 5)'}],['Dùng member p.x và p.y.','Đọc trực tiếp vào member.','In dấu ngoặc đúng mẫu.'],'#include <stdio.h>\nstruct Point{int x;int y;};\nint main(void){struct Point p;scanf("%d %d",&p.x,&p.y);printf("(%d, %d)\\n",p.x,p.y);return 0;}','struct nhóm các field liên quan thành một object.',['struct','members']],
    ['Student Information','easy',9,'Tạo struct Student gồm name và age; đọc một tên không khoảng trắng và tuổi, rồi in lại.','#include <stdio.h>\nstruct Student { char name[40]; int age; };\nint main(void) { struct Student s; return 0; }',[{input:'An 20',expected:'An is 20'},{input:'Mai 19',expected:'Mai is 19'}],['Dùng %39s cho tên.','Đọc age sau name.','Truy cập s.name và s.age.'],'#include <stdio.h>\nstruct Student{char name[40];int age;};\nint main(void){struct Student s;scanf("%39s %d",s.name,&s.age);printf("%s is %d\\n",s.name,s.age);return 0;}','Mảng char trong struct truyền trực tiếp cho scanf, không dùng &s.name.',['struct','scanf']],
    ['Array of Students','medium',12,'Đọc n sinh viên (tên, điểm), in tên sinh viên có điểm cao nhất.','#include <stdio.h>\nstruct Student { char name[40]; double score; };\nint main(void) { int n; scanf("%d",&n); return 0; }',[{input:'3\nAn 8.5\nBinh 9.2\nChi 7.8',expected:'Binh'},{input:'2\nA 10\nB 10',expected:'A'}],['Dùng mảng struct.','Khởi tạo best=0.','Chỉ thay khi score > best để giữ người đầu khi hòa.'],'#include <stdio.h>\nstruct Student{char name[40];double score;};\nint main(void){int n;struct Student a[100];scanf("%d",&n);for(int i=0;i<n;i++)scanf("%39s %lf",a[i].name,&a[i].score);int best=0;for(int i=1;i<n;i++)if(a[i].score>a[best].score)best=i;printf("%s\\n",a[best].name);return 0;}','Mỗi phần tử mảng là một bản ghi Student.',['struct','array']],
    ['Find Highest Score','medium',12,'Đọc danh sách sinh viên và in tên cùng điểm cao nhất, dạng Name Score.','#include <stdio.h>\nstruct Student { char name[40]; double score; };\nint main(void) { return 0; }',[{input:'2\nLan 7.5\nMinh 8.75',expected:'Minh 8.75'}],['So sánh score.','Lưu index best.','In %.2f.'],'#include <stdio.h>\nstruct Student{char name[40];double score;};\nint main(void){int n;struct Student a[100];scanf("%d",&n);for(int i=0;i<n;i++)scanf("%39s %lf",a[i].name,&a[i].score);int b=0;for(int i=1;i<n;i++)if(a[i].score>a[b].score)b=i;printf("%s %.2f\\n",a[b].name,a[b].score);return 0;}','Giữ cả tên và điểm bằng index của bản ghi tốt nhất.',['struct','max']],
    ['Student Management','hard',15,'Xây menu tối giản: 1 thêm sinh viên, 2 in danh sách, 0 thoát. Dùng struct và mảng cố định.','#include <stdio.h>\nstruct Student { char name[40]; double score; };\nint main(void) { /* implement menu */ return 0; }',[{input:'1 An 8.5 2 0',expected:'An 8.50'},{input:'1 An 8 1 Binh 9 2 0',expected:'An 8.00\nBinh 9.00'}],['Dùng count để biết số bản ghi.','switch xử lý menu.','Không vượt kích thước mảng.'],'#include <stdio.h>\nstruct Student{char name[40];double score;};\nint main(void){struct Student a[100];int n=0,op;while(scanf("%d",&op)==1&&op){if(op==1&&n<100)scanf("%39s %lf",a[n].name,&a[n++].score);else if(op==2)for(int i=0;i<n;i++)printf("%s %.2f\\n",a[i].name,a[i].score);}return 0;}','Menu là bài ghép input, struct, loop và switch.',['struct','menu']]
  ]);
  add('File Handling',[
    ['Open File','easy',8,'Mở tệp data.txt để đọc; in Opened nếu thành công, Failed nếu không.','#include <stdio.h>\nint main(void) { FILE *f; return 0; }',[{input:'',expected:'Opened'}],['Dùng fopen với mode r.','Kiểm tra f != NULL.','Đóng file sau khi kiểm tra.'],'#include <stdio.h>\nint main(void){FILE *f=fopen("data.txt","r");if(f){puts("Opened");fclose(f);}else puts("Failed");return 0;}','fopen trả NULL khi không mở được.',['fopen','file']],
    ['Write File','easy',8,'Tạo/ghi tệp data.txt bằng một dòng Hello file!, rồi in Written.','#include <stdio.h>\nint main(void) { return 0; }',[{input:'',expected:'Written'}],['Mode w tạo hoặc ghi đè.','Dùng fputs.','Gọi fclose.'],'#include <stdio.h>\nint main(void){FILE *f=fopen("data.txt","w");if(!f)return 1;fputs("Hello file!\\n",f);fclose(f);puts("Written");return 0;}','Mode w ghi nội dung mới vào file.',['file','fputs']],
    ['Read File','medium',10,'Đọc từng dòng từ data.txt và in ra stdout, giữ nguyên newline.','#include <stdio.h>\nint main(void) { char line[200]; return 0; }',[{input:'',expected:'(contents of data.txt)'}],['Mở bằng r.','while(fgets(...)).','Không dùng feof làm điều kiện đọc.'],'#include <stdio.h>\nint main(void){FILE *f=fopen("data.txt","r");char line[200];if(!f)return 1;while(fgets(line,sizeof line,f))fputs(line,stdout);fclose(f);return 0;}','fgets trả NULL khi hết dữ liệu hoặc gặp lỗi.',['file','fgets']],
    ['Append File','medium',10,'Mở log.txt ở mode append, ghi một dòng event và đóng file.','#include <stdio.h>\nint main(void) { return 0; }',[{input:'',expected:'Appended'}],['Mode a giữ dữ liệu cũ.','Ghi newline.','In Appended sau fclose.'],'#include <stdio.h>\nint main(void){FILE *f=fopen("log.txt","a");if(!f)return 1;fputs("event\\n",f);fclose(f);puts("Appended");return 0;}','Mode a luôn ghi thêm ở cuối stream.',['file','append']],
    ['Count Lines in File','hard',15,'Đếm số dòng trong data.txt bằng fgets và in count.','#include <stdio.h>\nint main(void) { char line[200]; return 0; }',[{input:'',expected:'3'}],['Mỗi fgets thành công tăng count.','Mở file r.','Xử lý file không mở được.'],'#include <stdio.h>\nint main(void){FILE *f=fopen("data.txt","r");char line[200];int count=0;if(!f)return 1;while(fgets(line,sizeof line,f))count++;fclose(f);printf("%d\\n",count);return 0;}','Đếm theo số lần đọc được một dòng.',['file','count']]
  ]);
  window.cExercises=e;
})();
