(function () {
  const normalizeCode = (value) =>
    /\b(cout|cin|cerr|clog|endl|swap|sort|find|count|vector|string|array|map|optional|unique_ptr|make_unique|filesystem|regex)\b/.test(
      value,
    ) && !/using\s+namespace\s+std\s*;/.test(value)
      ? "using namespace std;\n" + value
      : value;
  const make = (
    id,
    topic,
    title,
    difficulty,
    description,
    starter,
    tests,
    hints,
    solution,
    explanation,
    tags,
  ) => ({
    id,
    slug: id.replace(/^cpp-ex-/, "").replace(/[^a-z0-9-]/g, "-"),
    topic,
    title,
    difficulty,
    estimatedTime:
      difficulty === "hard" ? 15 : difficulty === "medium" ? 10 : 6,
    description,
    starterCode: normalizeCode(starter),
    testCases: tests,
    hints,
    solution: normalizeCode(solution),
    explanation,
    tags,
  });
  const exercises = [];
  const add = (topic, items) =>
    items.forEach((x) =>
      exercises.push(
        make(
          "cpp-ex-" + String(exercises.length + 1).padStart(3, "0"),
          topic,
          ...x,
        ),
      ),
    );
  const basicStarter =
    "#include <iostream>\nint main() {\n    // Write your solution here\n    return 0;\n}";
  add("Basics", [
    [
      "Hello World",
      "easy",
      "In Hello, World! bằng cout.",
      basicStarter,
      [{ input: "", expected: "Hello, World!" }],
      [
        "Dùng #include <iostream>.",
        "Dùng cout.",
        "Chuỗi nằm trong dấu ngoặc kép.",
      ],
      '#include <iostream>\nint main() { cout << "Hello, World!\\n"; return 0; }',
      "cout ghi chuỗi ra stdout.",
      ["iostream", "cout"],
    ],
    [
      "Print Your Name",
      "easy",
      "In tên của bạn rồi in một dòng chào.",
      basicStarter,
      [{ input: "", expected: "An\nXin chao An" }],
      [
        "Dùng hai lệnh xuất.",
        "Thay An bằng tên muốn in.",
        "Mỗi dòng dùng \\n.",
      ],
      '#include <iostream>\nint main() { cout << "An\\nXin chao An\\n"; }',
      "Chuỗi có thể chứa newline.",
      ["cout", "output"],
    ],
    [
      "Sum Two Integers",
      "easy",
      "Đọc hai số nguyên và in tổng.",
      basicStarter,
      [
        { input: "5 7", expected: "12" },
        { input: "-5 10", expected: "5" },
      ],
      ["Khai báo hai int.", "Dùng cin.", "In a+b."],
      '#include <iostream>\nint main() { int a,b; cin>>a>>b; cout<<a+b<<"\\n"; }',
      "cin đọc vào hai biến rồi cộng.",
      ["cin", "arithmetic"],
    ],
    [
      "Rectangle Area",
      "easy",
      "Đọc dài/rộng số thực, in diện tích với 2 chữ số.",
      basicStarter,
      [{ input: "4 2.5", expected: "10.00" }],
      [
        "Dùng double.",
        "Diện tích = dài * rộng.",
        "Dùng fixed và setprecision.",
      ],
      "#include <iostream>\n#include <iomanip>\nint main() { double a,b; cin>>a>>b; cout<<std::fixed<<setprecision(2)<<a*b; }",
      "iomanip định dạng phần thập phân.",
      ["double", "iomanip"],
    ],
    [
      "Celsius Fahrenheit",
      "easy",
      "Đổi Celsius sang Fahrenheit: F=C*9/5+32.",
      basicStarter,
      [
        { input: "0", expected: "32.00" },
        { input: "100", expected: "212.00" },
      ],
      ["Dùng 9.0 và 5.0.", "Đọc double.", "In 2 chữ số."],
      "#include <iostream>\n#include <iomanip>\nint main() { double c; cin>>c; cout<<std::fixed<<setprecision(2)<<c*9.0/5.0+32; }",
      "Dùng số thực để không bị chia nguyên.",
      ["formula", "double"],
    ],
  ]);
  add("Variables & Types", [
    [
      "Integer Variable",
      "easy",
      "Đọc int và in theo mẫu Value: n.",
      basicStarter,
      [{ input: "42", expected: "Value: 42" }],
      ["Dùng int.", "In chuỗi rồi n.", "Có thể nối bằng <<."],
      '#include <iostream>\nint main(){int n;cin>>n;cout<<"Value: "<<n; }',
      "Kiểu int phù hợp số nguyên.",
      ["int", "cin"],
    ],
    [
      "Floating Average",
      "easy",
      "Đọc hai số thực và in trung bình.",
      basicStarter,
      [{ input: "8 10", expected: "9.00" }],
      ["Tổng rồi chia 2.0.", "Dùng double.", "Định dạng fixed."],
      "#include <iostream>\n#include <iomanip>\nint main(){double a,b;cin>>a>>b;cout<<std::fixed<<setprecision(2)<<(a+b)/2.0;}",
      "Phép chia số thực giữ phần lẻ.",
      ["double", "average"],
    ],
    [
      "Character Code",
      "easy",
      "Đọc char và in mã số của ký tự.",
      basicStarter,
      [
        { input: "A", expected: "65" },
        { input: "z", expected: "122" },
      ],
      ["Dùng char.", "cin >> c bỏ whitespace.", "cout << static_cast<int>(c)."],
      "#include <iostream>\nint main(){char c;cin>>c;cout<<static_cast<int>(c);}",
      "static_cast chuyển char sang int rõ ràng.",
      ["char", "cast"],
    ],
    [
      "Const Circle",
      "medium",
      "Đọc bán kính, tính chu vi với constexpr PI.",
      basicStarter,
      [{ input: "2", expected: "12.57" }],
      ["Chu vi = 2*PI*r.", "Dùng constexpr double.", "setprecision(2)."],
      "#include <iostream>\n#include <iomanip>\nint main(){constexpr double PI=3.141592653589793;double r;cin>>r;cout<<std::fixed<<setprecision(2)<<2*PI*r;}",
      "constexpr giữ hằng số compile-time.",
      ["const", "math"],
    ],
    [
      "Simple Calculator",
      "medium",
      "Đọc a, toán tử và b; xử lý + - * /.",
      basicStarter,
      [
        { input: "8 + 2", expected: "10.00" },
        { input: "8 / 2", expected: "4.00" },
      ],
      ["Đọc char op.", "Dùng switch.", "Kiểm tra chia 0."],
      "#include <iostream>\n#include <iomanip>\nint main(){double a,b;char op;cin>>a>>op>>b;double r=0;switch(op){case '+':r=a+b;break;case '-':r=a-b;break;case '*':r=a*b;break;case '/':if(b!=0)r=a/b;break;}cout<<std::fixed<<setprecision(2)<<r;}",
      "switch chọn phép tính theo ký tự.",
      ["switch", "operators"],
    ],
  ]);
  add("Conditions", [
    [
      "Positive Negative",
      "easy",
      "In Positive, Negative hoặc Zero.",
      basicStarter,
      [
        { input: "8", expected: "Positive" },
        { input: "-2", expected: "Negative" },
        { input: "0", expected: "Zero" },
      ],
      ["So sánh n với 0.", "Dùng if/else if/else.", "In đúng chữ."],
      '#include <iostream>\nint main(){int n;cin>>n;if(n>0)cout<<"Positive";else if(n<0)cout<<"Negative";else cout<<"Zero";}',
      "Ba nhánh bao phủ ba khả năng.",
      ["if", "comparison"],
    ],
    [
      "Even or Odd",
      "easy",
      "Kiểm tra số nguyên chẵn hay lẻ.",
      basicStarter,
      [
        { input: "8", expected: "Even" },
        { input: "7", expected: "Odd" },
      ],
      ["Dùng n%2.", "Phần dư 0 là chẵn.", "Dùng toán tử điều kiện nếu muốn."],
      '#include <iostream>\nint main(){int n;cin>>n;cout<<(n%2==0?"Even":"Odd");}',
      "Phép modulo kiểm tra phần dư.",
      ["if", "modulo"],
    ],
    [
      "Largest of Two",
      "easy",
      "In số lớn hơn trong hai số.",
      basicStarter,
      [
        { input: "5 9", expected: "9" },
        { input: "4 4", expected: "4" },
      ],
      ["So sánh a và b.", "Xử lý trường hợp bằng.", "In một giá trị."],
      "#include <iostream>\nint main(){int a,b;cin>>a>>b;cout<<(a>b?a:b);}",
      "Toán tử ?: chọn một trong hai giá trị.",
      ["if", "ternary"],
    ],
    [
      "Largest of Three",
      "medium",
      "In số lớn nhất trong ba số.",
      basicStarter,
      [{ input: "10 25 15", expected: "25" }],
      [
        "Khởi tạo max=a.",
        "So sánh b và c.",
        "Không khởi tạo max bằng 0 nếu có số âm.",
      ],
      "#include <iostream>\nint main(){int a,b,c;cin>>a>>b>>c;cout<<std::max(a,std::max(b,c));}",
      "std::max lồng nhau chọn giá trị lớn nhất.",
      ["if", "max"],
    ],
    [
      "Grade Classification",
      "hard",
      "Xếp loại A/B/C/D/F theo điểm.",
      basicStarter,
      [
        { input: "95", expected: "A" },
        { input: "82", expected: "B" },
        { input: "49", expected: "F" },
      ],
      ["Kiểm tra ngưỡng cao trước.", "Dùng else if.", "Điểm hợp lệ 0..100."],
      '#include <iostream>\nint main(){int s;cin>>s;if(s>=90)cout<<"A";else if(s>=80)cout<<"B";else if(s>=70)cout<<"C";else if(s>=50)cout<<"D";else cout<<"F";}',
      "Thứ tự điều kiện tránh nhánh rộng chặn nhánh hẹp.",
      ["if", "grading"],
    ],
  ]);
  add("Loops", [
    [
      "Print 1 to N",
      "easy",
      "In các số từ 1 đến n, cách nhau bằng khoảng trắng.",
      basicStarter,
      [{ input: "5", expected: "1 2 3 4 5" }],
      ["Dùng for.", "Bắt đầu 1.", "Dừng i<=n."],
      '#include <iostream>\nint main(){int n;cin>>n;for(int i=1;i<=n;i++){if(i>1)cout<<" ";cout<<i;}}',
      "for quản lý biến đếm.",
      ["for", "counter"],
    ],
    [
      "Sum 1 to N",
      "easy",
      "Tính tổng từ 1 đến n.",
      basicStarter,
      [{ input: "5", expected: "15" }],
      ["sum bắt đầu 0.", "Cộng i mỗi lượt.", "Dùng long long."],
      "#include <iostream>\nint main(){int n;long long s=0;cin>>n;for(int i=1;i<=n;i++)s+=i;cout<<s;}",
      "Accumulator giữ tổng.",
      ["for", "sum"],
    ],
    [
      "Multiplication Table",
      "easy",
      "In bảng nhân n từ 1 đến 10.",
      basicStarter,
      [
        {
          input: "3",
          expected:
            "3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15\n3 x 6 = 18\n3 x 7 = 21\n3 x 8 = 24\n3 x 9 = 27\n3 x 10 = 30",
        },
      ],
      ["Loop 1..10.", "Dùng << nối format.", "Xuống dòng từng dòng."],
      '#include <iostream>\nint main(){int n;cin>>n;for(int i=1;i<=10;i++)cout<<n<<" x "<<i<<" = "<<n*i<<"\\n";}',
      "Một loop tạo mười dòng.",
      ["for", "output"],
    ],
    [
      "Factorial",
      "medium",
      "Tính n! với n không âm.",
      basicStarter,
      [
        { input: "5", expected: "120" },
        { input: "0", expected: "1" },
      ],
      ["result bắt đầu 1.", "Nhân từ 2.", "0! = 1."],
      "#include <iostream>\nint main(){int n;unsigned long long r=1;cin>>n;for(int i=2;i<=n;i++)r*=i;cout<<r;}",
      "Giá trị khởi tạo xử lý luôn trường hợp 0.",
      ["loop", "factorial"],
    ],
    [
      "Fibonacci",
      "hard",
      "In n số Fibonacci đầu tiên: 0 1 1...",
      basicStarter,
      [{ input: "6", expected: "0 1 1 2 3 5" }],
      ["Giữ hai số trước.", "Cập nhật bằng biến tạm.", "Xử lý n=0."],
      '#include <iostream>\nint main(){int n;long long a=0,b=1;cin>>n;for(int i=0;i<n;i++){if(i)cout<<" ";cout<<a;long long next=a+b;a=b;b=next;}}',
      "Không cần mảng cho chuỗi Fibonacci.",
      ["loop", "sequence"],
    ],
  ]);
  add("Strings & Vectors", [
    [
      "String Length",
      "easy",
      "Đọc một dòng và in độ dài string.",
      basicStarter,
      [
        { input: "hello", expected: "5" },
        { input: "C++ language", expected: "12" },
      ],
      [
        "Dùng std::getline.",
        "Gọi size().",
        "Xử lý newline từ input trước đó nếu có.",
      ],
      "#include <iostream>\n#include <string>\nint main(){string s;std::getline(cin,s);cout<<s.size();}",
      "string tự quản lý độ dài.",
      ["string", "size"],
    ],
    [
      "Count Vowels",
      "medium",
      "Đếm nguyên âm không phân biệt hoa thường.",
      basicStarter,
      [
        { input: "Education", expected: "5" },
        { input: "rhythm", expected: "0" },
      ],
      ["Duyệt từng char.", "Dùng tolower.", "So sánh a,e,i,o,u."],
      "#include <iostream>\n#include <string>\n#include <cctype>\nint main(){string s;std::getline(cin,s);int n=0;for(unsigned char c:s){c=static_cast<unsigned char>(std::tolower(c));if(c=='a'||c=='e'||c=='i'||c=='o'||c=='u')++n;}cout<<n;}",
      "Range-based for duyệt string.",
      ["string", "loop"],
    ],
    [
      "Reverse String",
      "medium",
      "In một dòng string theo thứ tự ngược.",
      basicStarter,
      [{ input: "hello", expected: "olleh" }],
      [
        "Dùng reverse iterator hoặc index.",
        "Giữ khoảng trắng.",
        "In newline nếu cần.",
      ],
      "#include <iostream>\n#include <string>\n#include <algorithm>\nint main(){string s;std::getline(cin,s);std::reverse(s.begin(),s.end());cout<<s;}",
      "algorithm có reverse cho range string.",
      ["string", "algorithm"],
    ],
    [
      "Vector Sum",
      "easy",
      "Đọc n số vào vector và in tổng.",
      basicStarter,
      [{ input: "4\n1 2 3 4", expected: "10" }],
      ["Dùng vector<int>.", "push_back hoặc resize.", "Duyệt range-based."],
      "#include <iostream>\n#include <vector>\n#include <numeric>\nint main(){int n;cin>>n;vector<int>v(n);for(int&x:v)cin>>x;cout<<accumulate(v.begin(),v.end(),0);}",
      "vector có size runtime và accumulate tính tổng.",
      ["vector", "numeric"],
    ],
    [
      "Vector Maximum",
      "hard",
      "Đọc vector và in max cùng vị trí đầu tiên.",
      basicStarter,
      [{ input: "4\n2 9 3 9", expected: "9 1" }],
      ["Dùng max_element.", "Vị trí là iterator - begin.", "Đảm bảo n>0."],
      '#include <iostream>\n#include <vector>\n#include <algorithm>\nint main(){int n;cin>>n;vector<int>v(n);for(int&x:v)cin>>x;auto it=max_element(v.begin(),v.end());cout<<*it<<" "<<(it-v.begin());}',
      "max_element trả iterator tới phần tử lớn nhất đầu tiên.",
      ["vector", "algorithm"],
    ],
  ]);
  add("Functions & OOP", [
    [
      "Square Function",
      "easy",
      "Viết hàm square trả bình phương số nguyên.",
      basicStarter,
      [{ input: "4", expected: "16" }],
      ["Kiểu trả về int.", "return n*n.", "Gọi từ main."],
      "#include <iostream>\nint square(int n){return n*n;}\nint main(){int n;cin>>n;cout<<square(n);}",
      "Hàm tách phép tính khỏi input/output.",
      ["function", "return"],
    ],
    [
      "Swap References",
      "easy",
      "Viết swap(int&, int&) đổi chỗ hai số.",
      basicStarter,
      [{ input: "3 8", expected: "8 3" }],
      [
        "Tham chiếu trỏ tới object gốc.",
        "Dùng swap.",
        "Truyền a,b không dùng & ở call.",
      ],
      '#include <iostream>\n#include <utility>\nvoid swapValues(int& a,int& b){swap(a,b);}\nint main(){int a,b;cin>>a>>b;swapValues(a,b);cout<<a<<" "<<b;}',
      "Reference cho phép hàm thay đổi biến caller.",
      ["reference", "function"],
    ],
    [
      "Function Overload",
      "medium",
      "Tạo overload area cho hình vuông và hình chữ nhật.",
      basicStarter,
      [
        { input: "3", expected: "9" },
        { input: "3 4", expected: "12" },
      ],
      ["Cùng tên khác số tham số.", "Dùng double.", "Gọi đúng overload."],
      "#include <iostream>\ndouble area(double s){return s*s;}\ndouble area(double a,double b){return a*b;}\nint main(){double a;cin>>a;cout<<area(a);}",
      "Compiler chọn overload dựa trên chữ ký lời gọi.",
      ["overload", "function"],
    ],
    [
      "Class Counter",
      "medium",
      "Tạo class Counter có increment() và value() const.",
      basicStarter,
      [{ input: "3", expected: "3" }],
      ["State nên private.", "increment tăng state.", "Getter đánh dấu const."],
      "#include <iostream>\nclass Counter{int n{};public:void increment(){++n;}int value()const{return n;}};\nint main(){int n;cin>>n;Counter c;for(int i=0;i<n;i++)c.increment();cout<<c.value();}",
      "Class đóng gói state và hành vi.",
      ["class", "encapsulation"],
    ],
    [
      "Student Class",
      "hard",
      "Tạo class Student lưu tên và điểm, in học sinh đạt >=5.",
      basicStarter,
      [{ input: "2\nAn 8\nBinh 4", expected: "An" }],
      ["Dùng string.", "Constructor nhận field.", "Getter const."],
      '#include <iostream>\n#include <string>\nclass Student{string name;double score;public:Student(string n,double s):name{n},score{s}{}bool passed()const{return score>=5;}string getName()const{return name;}};\nint main(){int n;cin>>n;for(int i=0;i<n;i++){string name;double score;cin>>name>>score;Student s{name,score};if(s.passed())cout<<s.getName()<<"\\n";}}',
      "Constructor khởi tạo object và member function kiểm tra invariant.",
      ["class", "string"],
    ],
  ]);
  add("STL & Files", [
    [
      "Sort Values",
      "easy",
      "Đọc vector rồi sắp xếp tăng dần.",
      basicStarter,
      [{ input: "4\n3 1 4 2", expected: "1 2 3 4" }],
      ["Dùng sort.", "Range là begin/end.", "In cách nhau."],
      '#include <iostream>\n#include <vector>\n#include <algorithm>\nint main(){int n;cin>>n;vector<int>v(n);for(int&x:v)cin>>x;sort(v.begin(),v.end());for(int i=0;i<n;i++){if(i)cout<<" ";cout<<v[i];}}',
      "sort dùng iterator range.",
      ["sort", "vector"],
    ],
    [
      "Find Value",
      "easy",
      "Tìm giá trị x trong vector, in Found hoặc Missing.",
      basicStarter,
      [
        { input: "4\n1 3 5 7\n5", expected: "Found" },
        { input: "3\n1 2 3\n4", expected: "Missing" },
      ],
      ["Dùng find.", "So iterator với end.", "Đọc x sau vector."],
      '#include <iostream>\n#include <vector>\n#include <algorithm>\nint main(){int n;cin>>n;vector<int>v(n);for(int&x:v)cin>>x;int x;cin>>x;cout<<(find(v.begin(),v.end(),x)!=v.end()?"Found":"Missing");}',
      "find trả end nếu không tìm thấy.",
      ["find", "vector"],
    ],
    [
      "Word Frequency",
      "medium",
      "Đọc n từ và in tần suất của một từ x.",
      basicStarter,
      [{ input: "4\na b a c\na", expected: "2" }],
      ["Dùng map hoặc unordered_map.", "Tăng count[word].", "Đọc x cuối."],
      "#include <iostream>\n#include <map>\n#include <string>\nint main(){int n;cin>>n;map<string,int>m;for(int i=0;i<n;i++){string w;cin>>w;++m[w];}string x;cin>>x;cout<<m[x];}",
      "map lưu key và count.",
      ["map", "frequency"],
    ],
    [
      "Write File",
      "medium",
      "Ghi một dòng vào data.txt và in Written.",
      basicStarter,
      [{ input: "Hello C++", expected: "Written" }],
      ["Dùng ofstream.", "Kiểm tra stream.", "Ghi input bằng getline."],
      '#include <iostream>\n#include <fstream>\n#include <string>\nint main(){string s;std::getline(cin,s);std::ofstream out{"data.txt"};if(!out)return 1;out<<s<<"\\n";cout<<"Written";}',
      "ofstream tự đóng khi ra khỏi scope và cần kiểm tra mở file.",
      ["fstream", "ofstream"],
    ],
    [
      "Read File",
      "hard",
      "Đọc data.txt và in số dòng.",
      basicStarter,
      [{ input: "", expected: "3" }],
      ["Dùng ifstream.", "while(getline(...)).", "Tăng count mỗi dòng."],
      '#include <iostream>\n#include <fstream>\n#include <string>\nint main(){std::ifstream in{"data.txt"};if(!in)return 1;string line;int count=0;while(std::getline(in,line))++count;cout<<count;}',
      "getline stream trả false khi hết file hoặc lỗi.",
      ["fstream", "ifstream"],
    ],
  ]);

  add("OOP", [
    [
      "Point Class",
      "easy",
      "Tạo class Point có constructor và method distanceSquared tới gốc.",
      "",
      [{ input: "3 4", expected: "25" }],
      ["Lưu x,y private.", "Trả x*x+y*y.", "Gọi method const."],
      "#include <iostream>\nclass Point{int x,y;public:Point(int a,int b):x{a},y{b}{}int distanceSquared()const{return x*x+y*y;}};int main(){int x,y;cin>>x>>y;cout<<Point{x,y}.distanceSquared();}",
      "Constructor khởi tạo state và method đọc state.",
      ["class", "constructor"],
    ],
    [
      "Bank Account",
      "medium",
      "Tạo class Account bảo vệ balance, có deposit và balance getter.",
      "",
      [{ input: "100 25", expected: "125" }],
      ["Balance private.", "deposit cộng tiền.", "Getter const."],
      "#include <iostream>\nclass Account{double balance;public:explicit Account(double b):balance{b}{}void deposit(double x){if(x>0)balance+=x;}double get()const{return balance;}};int main(){double b,d;cin>>b>>d;Account a{b};a.deposit(d);cout<<a.get();}",
      "Encapsulation bảo vệ invariant balance.",
      ["class", "encapsulation"],
    ],
    [
      "Shape Polymorphism",
      "medium",
      "Tạo interface Shape và class Circle override area.",
      "",
      [{ input: "2", expected: "12.57" }],
      ["Dùng virtual.", "PI là constexpr.", "Định dạng 2 số."],
      "#include <iostream>\n#include <iomanip>\nstruct Shape{virtual double area()const=0;virtual~Shape()=default;};struct Circle:Shape{double r;explicit Circle(double x):r{x}{}double area()const override{return 3.141592653589793*r*r;}};int main(){double r;cin>>r;cout<<std::fixed<<setprecision(2)<<Circle{r}.area();}",
      "Circle cung cấp implementation cho interface.",
      ["virtual", "override"],
    ],
    [
      "Copy and Move",
      "hard",
      "Tạo class Buffer dùng string để copy/move an toàn theo Rule of Zero.",
      "",
      [{ input: "hello", expected: "hello" }],
      ["Dùng string member.", "Không tự new/delete.", "Khởi tạo từ input."],
      "#include <iostream>\n#include <string>\nstruct Buffer{string data;};int main(){Buffer a{string{}},b;cin>>a.data;b=move(a);cout<<b.data;}",
      "RAII của string quản lý copy/move.",
      ["move", "rule-of-zero"],
    ],
    [
      "Operator +",
      "hard",
      "Overload operator+ cho Vector2 và in tổng hai vector.",
      "",
      [{ input: "1 2 3 4", expected: "4 6" }],
      ["Operator nhận const reference.", "Cộng từng field.", "Trả object mới."],
      '#include <iostream>\nstruct Vector2{int x,y;Vector2 operator+(const Vector2&o)const{return{x+o.x,y+o.y};}};int main(){Vector2 a,b;cin>>a.x>>a.y>>b.x>>b.y;auto c=a+b;cout<<c.x<<" "<<c.y;}',
      "Overload giữ phép cộng trực quan cho kiểu dữ liệu.",
      ["operator", "oop"],
    ],
  ]);
  add("Templates", [
    [
      "Template Maximum",
      "easy",
      "Viết function template maxValue cho int và double.",
      "",
      [{ input: "3 5", expected: "5" }],
      ["Dùng template<class T>.", "So sánh bằng >.", "Trả T."],
      "#include <iostream>\ntemplate<class T>T maxValue(T a,T b){return a>b?a:b;}int main(){int a,b;cin>>a>>b;cout<<maxValue(a,b);}",
      "Compiler sinh phiên bản phù hợp kiểu.",
      ["template", "generic"],
    ],
    [
      "Template Sum",
      "easy",
      "Viết template sumRange tính tổng vector số.",
      "",
      [{ input: "4 1 2 3 4", expected: "10" }],
      [
        "Nhận const vector<T>&.",
        "Accumulator cùng kiểu.",
        "Duyệt range-based.",
      ],
      "#include <iostream>\n#include <vector>\ntemplate<class T>T sumRange(const vector<T>&v){T s{};for(const T&x:v)s+=x;return s;}int main(){int n;cin>>n;vector<int>v(n);for(int&x:v)cin>>x;cout<<sumRange(v);}",
      "Template tái sử dụng thuật toán cho nhiều T.",
      ["template", "vector"],
    ],
    [
      "Class Template Box",
      "medium",
      "Tạo Box<T> có value() const.",
      "",
      [{ input: "42", expected: "42" }],
      ["Member kiểu T.", "Constructor nhận T.", "Getter const."],
      "#include <iostream>\ntemplate<class T>class Box{T value_;public:explicit Box(T v):value_{v}{}const T&value()const{return value_;}};int main(){int n;cin>>n;cout<<Box<int>{n}.value();}",
      "Class template tham số hóa kiểu lưu trữ.",
      ["template", "class"],
    ],
    [
      "Fold Expression",
      "medium",
      "Viết sum nhận số lượng int bất kỳ bằng fold expression.",
      "",
      [{ input: "", expected: "10" }],
      [
        "Dùng template<class...T>.",
        "Fold (... + values).",
        "Gọi sum(1,2,3,4).",
      ],
      "#include <iostream>\ntemplate<class...T>auto sum(T...values){return(...+values);}int main(){cout<<sum(1,2,3,4);}",
      "Fold expression gộp parameter pack.",
      ["template", "fold"],
    ],
    [
      "Concept Integral",
      "hard",
      "Viết hàm twice chỉ nhận kiểu integral bằng concept.",
      "",
      [{ input: "4", expected: "8" }],
      ["Include concepts.", "Dùng integral.", "Trả x*2."],
      "#include <concepts>\n#include <iostream>\ntemplate<integral T>T twice(T x){return x*2;}int main(){int n;cin>>n;cout<<twice(n);}",
      "Constraint báo lỗi sớm khi kiểu không phù hợp.",
      ["concepts", "template"],
    ],
  ]);
  add("Memory Safety", [
    [
      "Unique Pointer",
      "easy",
      "Dùng make_unique để tạo int và in giá trị.",
      "",
      [{ input: "7", expected: "7" }],
      ["Dùng <memory>.", "Dereference unique_ptr.", "Không gọi delete."],
      "#include <iostream>\n#include <memory>\nint main(){int n;cin>>n;auto p=make_unique<int>(n);cout<<*p;}",
      "RAII tự giải phóng khi p ra khỏi scope.",
      ["raii", "unique_ptr"],
    ],
    [
      "Optional Parse",
      "easy",
      "Trả optional<int> nếu input không âm, ngược lại no value.",
      "",
      [
        { input: "5", expected: "5" },
        { input: "-1", expected: "0" },
      ],
      ["Dùng optional.", "Trả nullopt cho âm.", "value_or(0)."],
      "#include <iostream>\n#include <optional>\noptional<int> parse(int n){if(n<0)return nullopt;return n;}int main(){int n;cin>>n;cout<<parse(n).value_or(0);}",
      "optional biểu diễn kết quả có thể không tồn tại.",
      ["optional", "safety"],
    ],
    [
      "Weak Pointer",
      "medium",
      "Dùng weak_ptr lock để kiểm tra object còn sống.",
      "",
      [{ input: "", expected: "alive" }],
      ["Tạo shared_ptr.", "Gán weak_ptr.", "lock trước khi dereference."],
      '#include <iostream>\n#include <memory>\nint main(){auto owner=make_shared<int>(1);weak_ptr<int> view=owner;cout<<(view.lock()?"alive":"expired");}',
      "weak_ptr không giữ ownership.",
      ["weak_ptr", "ownership"],
    ],
    [
      "Bounds Checked Access",
      "medium",
      "Đọc index vector bằng at(), in Value hoặc OutOfRange.",
      "",
      [
        { input: "3\n1 2 3\n1", expected: "Value 2" },
        { input: "3\n1 2 3\n5", expected: "OutOfRange" },
      ],
      ["Dùng v.at(index).", "Bắt out_of_range.", "Index tính từ 0."],
      '#include <iostream>\n#include <vector>\n#include <stdexcept>\nint main(){int n,i;cin>>n;vector<int>v(n);for(int&x:v)cin>>x;cin>>i;try{cout<<"Value "<<v.at(i);}catch(const out_of_range&){cout<<"OutOfRange";}}',
      "at kiểm tra biên và ném exception.",
      ["vector", "bounds"],
    ],
    [
      "Exception Safe Update",
      "hard",
      "Cập nhật vector theo strong guarantee bằng bản sao rồi swap.",
      "",
      [{ input: "3\n1 2 3\n4", expected: "1 2 3 4" }],
      ["Copy vector.", "Thay đổi bản sao.", "swap sau khi thành công."],
      '#include <iostream>\n#include <vector>\nvoid append(vector<int>&v,int x){auto copy=v;copy.push_back(x);v.swap(copy);}int main(){int n,x;cin>>n;vector<int>v(n);for(int&a:v)cin>>a;cin>>x;append(v,x);for(int a:v)cout<<a<<" ";}',
      "State gốc chỉ đổi sau thao tác thành công.",
      ["exception-safety", "vector"],
    ],
  ]);
  add("Modern C++", [
    [
      "Structured Bindings",
      "easy",
      "Đọc pair và in name cùng score bằng structured binding.",
      "",
      [{ input: "", expected: "An 9" }],
      ["Tạo pair.", "auto [name,score].", "In hai biến."],
      '#include <iostream>\n#include <utility>\nint main(){auto [name,score]=pair{"An",9};cout<<name<<" "<<score;}',
      "Structured binding đặt tên cho các thành phần.",
      ["pair", "modern"],
    ],
    [
      "String View",
      "easy",
      "Viết hàm nhận string_view và in size.",
      "",
      [{ input: "hello", expected: "5" }],
      ["Dùng string_view.", "getline input.", "Không sở hữu dữ liệu."],
      "#include <iostream>\n#include <string>\n#include <string_view>\nvoid printSize(string_view s){cout<<s.size();}int main(){string s;std::getline(cin,s);printSize(s);}",
      "string_view là view không copy.",
      ["string_view", "api"],
    ],
    [
      "Filesystem Extension",
      "medium",
      "Đọc tên file và in extension bằng filesystem::path.",
      "",
      [{ input: "report.txt", expected: ".txt" }],
      ["Tạo path.", "Gọi extension().string().", "Include filesystem."],
      "#include <iostream>\n#include <filesystem>\nint main(){string name;cin>>name;cout<<filesystem::path{name}.extension().string();}",
      "path xử lý thành phần đường dẫn portable.",
      ["filesystem", "path"],
    ],
    [
      "Chrono Duration",
      "medium",
      "Đọc hai số milliseconds và in duration giữa chúng.",
      "",
      [{ input: "100 250", expected: "150" }],
      ["Dùng milliseconds.", "Tạo duration.", "Trừ rồi count."],
      "#include <iostream>\n#include <chrono>\nint main(){long long a,b;cin>>a>>b;auto d=chrono::milliseconds{b}-chrono::milliseconds{a};cout<<d.count();}",
      "chrono giữ đơn vị thời gian trong kiểu.",
      ["chrono", "duration"],
    ],
    [
      "Regex Validation",
      "hard",
      "Kiểm tra chuỗi chỉ gồm chữ số bằng regex.",
      "",
      [
        { input: "2026", expected: "Valid" },
        { input: "20a6", expected: "Invalid" },
      ],
      ["Pattern [0-9]+.", "Dùng regex_match.", "In đúng trạng thái."],
      '#include <iostream>\n#include <regex>\nint main(){string s;cin>>s;cout<<(regex_match(s,regex{"[0-9]+"})?"Valid":"Invalid");}',
      "regex_match yêu cầu toàn bộ chuỗi khớp.",
      ["regex", "validation"],
    ],
  ]);
  window.cppExercises = exercises;
})();
