(function () {
  const normalizeCode = (value) =>
    /\b(cout|cin|cerr|clog|endl|swap|sort|find|count|vector|string|array|map|set|stack|queue|optional|unique_ptr|make_unique|filesystem|regex)\b/.test(
      value,
    ) && !/using\s+namespace\s+std\s*;/.test(value)
      ? "using namespace std;\n" + value
      : value;
  const make = (id, topic, title, difficulty, description, starter, tests, hints, solution, explanation, tags) => ({
    id,
    slug: id.replace(/^cpp-ex-/, "").replace(/[^a-z0-9-]/g, "-"),
    topic, title, difficulty,
    estimatedTime: difficulty === "hard" ? 15 : difficulty === "medium" ? 10 : 6,
    description,
    starterCode: normalizeCode(starter),
    testCases: tests,
    hints,
    solution: normalizeCode(solution),
    explanation, tags,
  });
  const exercises = [];
  const add = (topic, items) =>
    items.forEach((x) =>
      exercises.push(
        make("cpp-ex-" + String(exercises.length + 1).padStart(3, "0"), topic, ...x),
      ),
    );
  add("01 · C++ Cơ bản", [
    ["Hello, World!", "easy", "In ra đúng dòng chữ: Hello, World!", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "", "expected": "Hello, World!"}], ["Dung cout trong iostream.", "Chuoi nam trong dau ngoac kep.", "Ket thuc cau lenh bang dau ;"], "#include <iostream>\nusing namespace std;\nint main() {\n    cout << \"Hello, World!\";\n    return 0;\n}", "cout gui noi dung ra man hinh, van than ngoac kep bao quanh chuoi.", ["cout", "output", "hello"]],
    ["In nhiều dòng", "easy", "In ra hai dong: I am learning C++ va It is fun!", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "", "expected": "I am learning C++\nIt is fun!"}], ["Dung hai lenh cout.", "Xuong dong bang \\n hoac endl."], "#include <iostream>\nusing namespace std;\nint main() {\n    cout << \"I am learning C++\\n\";\n    cout << \"It is fun!\";\n    return 0;\n}", "Moi lenh cout in mot phan; \\n day con tro xuong dong moi.", ["cout", "output", "newline"]],
    ["In số 1 đến 5", "easy", "In cac so 1, 2, 3, 4, 5, moi so nam tren mot dong (khong dung vong lap cung duoc).", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "", "expected": "1\n2\n3\n4\n5"}], ["Co the dung 5 lenh cout.", "Hoac dung cout << \"1\\n2\\n3\\n4\\n5\"."], "#include <iostream>\nusing namespace std;\nint main() {\n    cout << \"1\\n2\\n3\\n4\\n5\";\n    return 0;\n}", "Ky tu \\n tao dong moi nen 5 so xuong 5 dong.", ["cout", "output", "numbers"]],
    ["Comment và số 42", "easy", "In ra 42. Loi giai can co it nhat mot comment (//) giai thich viec lam.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "", "expected": "42"}], ["Comment // khong anh huong den chay.", "cout << 42 in so ma khong can ngoac kep."], "#include <iostream>\nusing namespace std;\nint main() {\n    // In gia tri 42 ra man hinh\n    cout << 42;\n    return 0;\n}", "Comment bi trinh bien dich bo qua; so khong can ngoac kep khi in.", ["comments", "cout", "numbers"]],
    ["Ký tự đặc biệt", "medium", "In ra chinh xac hai dong:\n\"C++\" is \"fun\"\nPath: C:\\new", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "", "expected": "\"C++\" is \"fun\"\nPath: C:\\new"}], ["Escape dau nhay kep bang \\\".", "Escape dau \\\\ bang \\\\."], "#include <iostream>\nusing namespace std;\nint main() {\n    cout << \"\\\"C++\\\" is \\\"fun\\\"\\n\";\n    cout << \"Path: C:\\\\new\";\n    return 0;\n}", "Dau \\ cho phep in ky tu dac biet: \" la dau nhay, \\\\ la gach cheo.", ["escape", "cout", "special-characters"]],
  ]);
  add("02 · Biến & Kiểu dữ liệu", [
    ["Biến và tổng", "easy", "Tao hai bien int x = 10 va y = 3, in ra tong cua chung.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "", "expected": "13"}], ["Khai bao int x = 10;", "cout << x + y."], "#include <iostream>\nusing namespace std;\nint main() {\n    int x = 10;\n    int y = 3;\n    cout << x + y;\n    return 0;\n}", "Bien luu gia tri va co the dung trong bieu thuc ngay lap tuc.", ["variables", "int", "output"]],
    ["Tổng ba số", "easy", "Doc ba so nguyen tu ban phim va in ra tong.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "1 2 3", "expected": "6"}, {"input": "10 -4 5", "expected": "11"}, {"input": "0 0 0", "expected": "0"}], ["Dung cin >> a >> b >> c.", "Cong ba bien roi in ra."], "#include <iostream>\nusing namespace std;\nint main() {\n    int a, b, c;\n    cin >> a >> b >> c;\n    cout << a + b + c;\n    return 0;\n}", "cin co the doc nhieu gia tri lien tiep cach nhau boi khoang trang.", ["input", "variables", "int", "sum"]],
    ["Hằng số thuế", "medium", "Khai bao const int TAX = 10 (phan tram). Doc gia tien (int), in ra thue phai tra = price * TAX / 100.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "200", "expected": "20"}, {"input": "50", "expected": "5"}, {"input": "137", "expected": "13"}], ["const ngia la khong the gan lai.", "Nhan truoc chia sau de giu phan nguyen."], "#include <iostream>\nusing namespace std;\nint main() {\n    const int TAX = 10;\n    int price;\n    cin >> price;\n    cout << price * TAX / 100;\n    return 0;\n}", "Gia gan voi const khong the bi thay doi ve sau; phep chia nguyen lam tron xuong.", ["constants", "variables", "int"]],
    ["Chào tên", "easy", "Doc mot tu (ten) va in ra: Hello, <ten>!", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "Lan", "expected": "Hello, Lan!"}, {"input": "Cuong", "expected": "Hello, Cuong!"}], ["Doc string bang cin.", "Noi chuoi bang toan tu +."], "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string name;\n    cin >> name;\n    cout << \"Hello, \" + name + \"!\";\n    return 0;\n}", "Toan tu + ghep cac string lai thanh mot chuoi moi.", ["strings", "input", "variables"]],
    ["Mã ASCII của ký tự", "medium", "Doc mot ky tu va in ra ma ASCII (so nguyen) cua no.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "A", "expected": "65"}, {"input": "0", "expected": "48"}, {"input": "z", "expected": "122"}], ["Kieu char luu dung ma so.", "Ep kieu (int) c de in ra so."], "#include <iostream>\nusing namespace std;\nint main() {\n    char c;\n    cin >> c;\n    cout << (int)c;\n    return 0;\n}", "char ban chat la so nguyen nho nen ep (int) se to lo ma ASCII.", ["char", "data-types", "type-casting"]],
    ["Trung bình với auto", "easy", "Doc hai so nguyen, dung auto tinh trung binh cong (phep chia nguyen).", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "3 4", "expected": "3"}, {"input": "10 20", "expected": "15"}, {"input": "-3 6", "expected": "1"}], ["auto tu suy luan kieu tu bieu thuc.", "(a + b) / 2 la phep chia nguyen."], "#include <iostream>\nusing namespace std;\nint main() {\n    int a, b;\n    cin >> a >> b;\n    auto avg = (a + b) / 2;\n    cout << avg;\n    return 0;\n}", "auto giup compiler tu chon kieu; o day bieu thuc int cho ra int.", ["auto", "type-casting", "operators"]],
  ]);
  add("03 · Toán tử", [
    ["Đủ cả phép toán", "easy", "Doc hai so nguyen a, b. In lan luot tong, hieu, tich, thuong (nguyen), so du - moi ket qua mot dong.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "7 3", "expected": "10\n4\n21\n2\n1"}, {"input": "10 5", "expected": "15\n5\n50\n2\n0"}], ["Dung + - * / %.", "In theo thu tu: tong, hieu, tich, thuong, so du."], "#include <iostream>\nusing namespace std;\nint main() {\n    int a, b;\n    cin >> a >> b;\n    cout << a + b << \"\\n\";\n    cout << a - b << \"\\n\";\n    cout << a * b << \"\\n\";\n    cout << a / b << \"\\n\";\n    cout << a % b;\n    return 0;\n}", "Toan tu % cho so du; chia hai so nguyen cho ket qua nguyen (lam tron xuong).", ["operators", "arithmetic", "modulo"]],
    ["Toán tử gán kết hợp", "medium", "Doc x. Thuc hien lan luot: x += 10; x *= 2; x -= 6. In ket qua.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "3", "expected": "20"}, {"input": "5", "expected": "24"}, {"input": "-1", "expected": "12"}], ["x += 10 giong x = x + 10.", "Lam lan luot theo thu tu."], "#include <iostream>\nusing namespace std;\nint main() {\n    int x;\n    cin >> x;\n    x += 10;\n    x *= 2;\n    x -= 6;\n    cout << x;\n    return 0;\n}", "Toan tu gan ket hop (+=, *=, -=) viet gon cua phep toan roi gan lai.", ["operators", "assignment"]],
    ["So sánh hai số", "easy", "Doc a, b. In Greater neu a > b, Equal neu bang, nguyen tac in Less.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "5 2", "expected": "Greater"}, {"input": "4 4", "expected": "Equal"}, {"input": "1 9", "expected": "Less"}], ["Dung if / else if / else.", "So sanh bang == khac voi gan =."], "#include <iostream>\nusing namespace std;\nint main() {\n    int a, b;\n    cin >> a >> b;\n    if (a > b)\n        cout << \"Greater\";\n    else if (a == b)\n        cout << \"Equal\";\n    else\n        cout << \"Less\";\n    return 0;\n}", "Toan tu so sanh cho gia tri bool dung trong dieu kien if.", ["operators", "comparison", "conditions"]],
    ["Điều kiện cần và đủ", "medium", "Doc tuoi va ky tu co-giay-to (Y/N). In Admit neu du 18 tuoi VA co giay to, nguoc lai in Deny.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "20 Y", "expected": "Admit"}, {"input": "17 Y", "expected": "Deny"}, {"input": "20 N", "expected": "Deny"}], ["Dung toan tu logic &&.", "So sanh ky tu bang == 'Y'."], "#include <iostream>\nusing namespace std;\nint main() {\n    int age;\n    char id;\n    cin >> age >> id;\n    if (age >= 18 && id == 'Y')\n        cout << \"Admit\";\n    else\n        cout << \"Deny\";\n    return 0;\n}", "&& chi dung khi ca ve trai va ve phai deu dung.", ["operators", "logical", "boolean"]],
    ["Chẵn hay lẻ", "easy", "Doc mot so nguyen, in Even neu so chan, Odd neu so le.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "8", "expected": "Even"}, {"input": "7", "expected": "Odd"}, {"input": "0", "expected": "Even"}], ["So chan co n % 2 == 0.", "Toan tu % cho so chia het cho 2."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    cout << (n % 2 == 0 ? \"Even\" : \"Odd\");\n    return 0;\n}", "n % 2 cho biet so du khi chia 2 - day la cach kinh dien de kiem tra chan le.", ["modulo", "operators", "conditions"]],
    ["Độ ưu tiên phép toán", "hard", "Doc ba so nguyen a, b, c. Tinh va in gia tri cua bieu thuc: a + b * c - a / b", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "10 2 3", "expected": "11"}, {"input": "9 3 4", "expected": "18"}, {"input": "8 4 2", "expected": "14"}], ["Nhan/chia truoc, cong/tru sau.", "Tinh: 10 + (2*3) - (10/2) = 11."], "#include <iostream>\nusing namespace std;\nint main() {\n    int a, b, c;\n    cin >> a >> b >> c;\n    cout << a + b * c - a / b;\n    return 0;\n}", "Toan tu nhan va chia co do uu tien cao hon cong tru nen chay truoc.", ["operators", "precedence"]],
  ]);
  add("04 · Chuỗi (Strings)", [
    ["Nối chuỗi", "easy", "Doc hai tu. In ra chung cach nhau boi mot dau cach va ket thuc bang dau cham than.", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "Xin chao", "expected": "Xin chao!"}, {"input": "Hello World", "expected": "Hello World!"}], ["cin >> tu dung lai o khoang trang.", "Noi bang toan tu +."], "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string a, b;\n    cin >> a >> b;\n    cout << a + \" \" + b + \"!\";\n    return 0;\n}", "Cung kieu string nen co the noi truc tiep bang dau +.", ["strings", "concatenation"]],
    ["Độ dài chuỗi", "easy", "Doc mot tu va in ra do dai cua no.", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "Hello", "expected": "5"}, {"input": "C++", "expected": "3"}, {"input": "Vietnam", "expected": "7"}], ["Dung ham size() hoac length()."], "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string s;\n    cin >> s;\n    cout << s.size();\n    return 0;\n}", "size() tra ve so ky tu trong string.", ["strings", "length", "size"]],
    ["Ký tự đầu và cuối", "medium", "Doc mot tu. In ky tu dau va ky tu cuoi, cach nhau boi mot dau cach.", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "C++", "expected": "C +"}, {"input": "abc", "expected": "a c"}, {"input": "a", "expected": "a a"}], ["Truy cap s[0] va s[s.size() - 1]."], "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string s;\n    cin >> s;\n    cout << s[0] << \" \" << s[s.size() - 1];\n    return 0;\n}", "String cho truy cap tung ky tu nhu mang, chi so bat dau tu 0.", ["strings", "index", "access"]],
    ["Đọc cả một dòng", "medium", "Doc CA MOT dong (co khoang trang) va in ra: You said: <dong do>", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "I love C++", "expected": "You said: I love C++"}, {"input": "hi", "expected": "You said: hi"}], ["cin >> dung o dau khoang trang.", "Dung getline(cin, s) de lay ca dong."], "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string s;\n    getline(cin, s);\n    cout << \"You said: \" << s;\n    return 0;\n}", "getline doc den het ky tu xuong dong nen giu lai khoang trang trong chuoi.", ["strings", "getline", "input"]],
    ["Đảo họ tên", "medium", "Doc ten va ho (hai tu theo thu tu: ten, ho). In theo dinh dang: Ho, Ten", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "Van Anh", "expected": "Anh, Van"}, {"input": "Xuan Hoang", "expected": "Hoang, Xuan"}], ["Doc hai string bang cin.", "Dao thu tu khi in va them dau phay."], "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string first, last;\n    cin >> first >> last;\n    cout << last << \", \" << first;\n    return 0;\n}", "Doc va in la hai buoc tach biet: thu tu in hoan toan do ta chon.", ["strings", "input", "output"]],
    ["Đếm từ trong dòng", "hard", "Doc mot dong (co the co nhieu khoang trang lien tiep). In ra so tu trong dong.", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "one two three", "expected": "3"}, {"input": "  a  bb   ccc ", "expected": "3"}, {"input": "hello", "expected": "1"}], ["Dung istringstream trong <sstream>.", "Toan tu >> cua dong bo bo qua khoang trang thua."], "#include <iostream>\n#include <sstream>\n#include <string>\nusing namespace std;\nint main() {\n    string line, w;\n    getline(cin, line);\n    istringstream is(line);\n    int c = 0;\n    while (is >> w)\n        c++;\n    cout << c;\n    return 0;\n}", "istringstream bien dong thanh dong chay de doc tung tu, tu dong bo khoang trang thua.", ["strings", "loops", "sstream", "count"]],
  ]);
  add("05 · Toán học & Boolean", [
    ["Căn bậc hai nguyên", "easy", "Doc so nguyen n (0 <= n <= 1000). In ra phan nguyen cua sqrt(n).", "#include <iostream>\n#include <cmath>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "16", "expected": "4"}, {"input": "20", "expected": "4"}, {"input": "9", "expected": "3"}, {"input": "1", "expected": "1"}], ["Dung sqrt trong <cmath>.", "Ep kieu (int) de bo phan thap phan."], "#include <iostream>\n#include <cmath>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    cout << (int)sqrt(n);\n    return 0;\n}", "sqrt tra ve double; ep (int) se cat bo phan thap phan.", ["math", "sqrt", "type-casting"]],
    ["Lũy thừa nguyên", "medium", "Doc base va exp (so nguyen duong). In base mu exp, khong dung pow.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "2 10", "expected": "1024"}, {"input": "3 3", "expected": "27"}, {"input": "5 1", "expected": "5"}], ["Vong lap lap lai exp lan.", "Bat dau ket qua la 1 roi nhan voi base."], "#include <iostream>\nusing namespace std;\nint main() {\n    int base, exp;\n    cin >> base >> exp;\n    int r = 1;\n    for (int i = 0; i < exp; i++)\n        r *= base;\n    cout << r;\n    return 0;\n}", "a^n la nhan a voi chinh no n lan; vong lap giup khong can ham pow.", ["math", "loops", "power"]],
    ["Min và Max", "easy", "Doc ba so nguyen. In gia tri nho nhat va lon nhat, cach nhau mot dau cach.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "4 9 2", "expected": "2 9"}, {"input": "5 5 5", "expected": "5 5"}, {"input": "-1 -9 0", "expected": "-9 0"}], ["Khoi tao min = max = so dau.", "Cap nhat khi thay so nho/lon hon."], "#include <iostream>\nusing namespace std;\nint main() {\n    int a, b, c;\n    cin >> a >> b >> c;\n    int mn = a, mx = a;\n    if (b < mn) mn = b;\n    if (c < mn) mn = c;\n    if (b > mx) mx = b;\n    if (c > mx) mx = c;\n    cout << mn << \" \" << mx;\n    return 0;\n}", "Giat min/max qua tung so la cach thu cong, khong can thu vien.", ["math", "min", "max", "conditions"]],
    ["Giá trị tuyệt đối", "easy", "Doc mot so nguyen va in gia tri tuyet doi cua no (khong dung abs).", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "-5", "expected": "5"}, {"input": "12", "expected": "12"}, {"input": "0", "expected": "0"}], ["Neu n < 0 thi in ra -n."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    if (n < 0)\n        cout << -n;\n    else\n        cout << n;\n    return 0;\n}", "Tri tuyet doi la khoang cach den 0 nen so am dao dau thanh duong.", ["math", "abs", "boolean"]],
    ["Năm nhuận", "medium", "Doc nam (int). In Yes neu la nam nhuan, nguoc lai in No. Nam nhuan: chia het 4 VA (khong chia het 100 HOAC chia het 400).", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "2024", "expected": "Yes"}, {"input": "1900", "expected": "No"}, {"input": "2000", "expected": "Yes"}, {"input": "2023", "expected": "No"}], ["Dung && va ||.", "Chia het cho 4: n % 4 == 0."], "#include <iostream>\nusing namespace std;\nint main() {\n    int y;\n    cin >> y;\n    bool leap = (y % 4 == 0 && y % 100 != 0) || y % 400 == 0;\n    cout << (leap ? \"Yes\" : \"No\");\n    return 0;\n}", "Bieu thuc logic ghep && / || cho ra mot bool dung theo quy tac nam nhuan Gregorian.", ["boolean", "operators", "conditions", "leap-year"]],
  ]);
  add("06 · Điều kiện & Switch", [
    ["Dương, âm hay không", "easy", "Doc mot so nguyen va in Positive, Negative hoac Zero.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "5", "expected": "Positive"}, {"input": "-3", "expected": "Negative"}, {"input": "0", "expected": "Zero"}], ["Ba nhanh if / else if / else."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    if (n > 0)\n        cout << \"Positive\";\n    else if (n < 0)\n        cout << \"Negative\";\n    else\n        cout << \"Zero\";\n    return 0;\n}", "if/else if/else kiem tra lan luot va dung o nhanh dau tien thoa man.", ["conditions", "if-else"]],
    ["Xếp loại điểm", "medium", "Doc diem (0-100). Xep loai: >=90 A, >=80 B, >=60 C, >=40 D, con lai F.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "85", "expected": "B"}, {"input": "40", "expected": "D"}, {"input": "100", "expected": "A"}, {"input": "39", "expected": "F"}, {"input": "60", "expected": "C"}], ["Kiểm tra từ mức cao xuống thấp.", "Moi else if chi chay khi cac dieu kien tren sai."], "#include <iostream>\nusing namespace std;\nint main() {\n    int s;\n    cin >> s;\n    if (s >= 90)\n        cout << \"A\";\n    else if (s >= 80)\n        cout << \"B\";\n    else if (s >= 60)\n        cout << \"C\";\n    else if (s >= 40)\n        cout << \"D\";\n    else\n        cout << \"F\";\n    return 0;\n}", "Thu tu kiem tra tu cao xuong thap giup moi nhanh con lai khong can dieu kien duoi.", ["conditions", "if-else", "nested"]],
    ["Số lớn nhất bằng ternary", "easy", "Doc hai so va in so lon hon, dung toan tu ba ngoi ?:", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "3 9", "expected": "9"}, {"input": "12 7", "expected": "12"}, {"input": "4 4", "expected": "4"}], ["(a > b ? a : b) tra ve gia tri.", "cout co the in truc tiep bieu thuc."], "#include <iostream>\nusing namespace std;\nint main() {\n    int a, b;\n    cin >> a >> b;\n    cout << (a > b ? a : b);\n    return 0;\n}", "Toan tu ba ngoi la dang gon cua if/else khi chi chon mot trong hai gia tri.", ["conditions", "ternary", "operators"]],
    ["Menu đồ uống", "medium", "Doc so lua chon 1-4. In Coffee, Tea, Juice, Water tuong ung; gia tri khac in Invalid.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "1", "expected": "Coffee"}, {"input": "3", "expected": "Juice"}, {"input": "9", "expected": "Invalid"}], ["switch case ket hop break.", "Nhanh default xu ly gia tri ngoai list."], "#include <iostream>\nusing namespace std;\nint main() {\n    int op;\n    cin >> op;\n    switch (op) {\n        case 1: cout << \"Coffee\"; break;\n        case 2: cout << \"Tea\"; break;\n        case 3: cout << \"Juice\"; break;\n        case 4: cout << \"Water\"; break;\n        default: cout << \"Invalid\";\n    }\n    return 0;\n}", "switch so sanh gia tri nguyen voi tung case; break ngan chay lan sang case ke tiep.", ["conditions", "switch"]],
    ["Phân loại tuổi lồng if", "medium", "Doc tuoi. In Child (<13), Teen (13-19), Adult (20-59), Senior (>=60).", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "8", "expected": "Child"}, {"input": "13", "expected": "Teen"}, {"input": "25", "expected": "Adult"}, {"input": "70", "expected": "Senior"}, {"input": "19", "expected": "Teen"}], ["Mỗi nhóm chỉ cần kiểm tra mép trên.", "if lồng nhau hoặc else if đều được."], "#include <iostream>\nusing namespace std;\nint main() {\n    int age;\n    cin >> age;\n    if (age < 13)\n        cout << \"Child\";\n    else if (age <= 19)\n        cout << \"Teen\";\n    else if (age <= 59)\n        cout << \"Adult\";\n    else\n        cout << \"Senior\";\n    return 0;\n}", "Vao nhanh sau co nghia da loai tru cac truong hop o nhanh truoc nen chi can kiem tra bien tren.", ["conditions", "nested"]],
    ["Rút tiền ATM", "hard", "Doc so du va so tien muon rut. Neu so tien khong chia het 500: in Invalid amount. Neu vuot so du: in Not enough. Nguoc lai in so du con lai.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "1000 500", "expected": "500"}, {"input": "1000 300", "expected": "Invalid amount"}, {"input": "1000 1500", "expected": "Not enough"}, {"input": "1000 1000", "expected": "0"}], ["Kiểm tra điều kiện hợp lệ trước khả năng chi trả.", "Chia het 500: amount % 500 == 0."], "#include <iostream>\nusing namespace std;\nint main() {\n    int balance, amount;\n    cin >> balance >> amount;\n    if (amount % 500 != 0)\n        cout << \"Invalid amount\";\n    else if (amount > balance)\n        cout << \"Not enough\";\n    else\n        cout << balance - amount;\n    return 0;\n}", "Ham kiem tra (hop le truoc, du tien sau) lam viec rut chay dung nhu ATM that.", ["conditions", "if-else", "modulo"]],
  ]);
  add("07 · Vòng lặp", [
    ["Đếm từ 1 đến n", "easy", "Doc n (1 <= n <= 20). In cac so 1 den n, moi so mot dong.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "5", "expected": "1\n2\n3\n4\n5"}, {"input": "1", "expected": "1"}], ["for (int i = 1; i <= n; i++)."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    for (int i = 1; i <= n; i++)\n        cout << i << \"\\n\";\n    return 0;\n}", "Vong for lap lai tang dan bien dem tu 1 den n.", ["loops", "for"]],
    ["Tổng 1 đến n", "easy", "Doc n va in tong cac so tu 1 den n.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "5", "expected": "15"}, {"input": "100", "expected": "5050"}, {"input": "1", "expected": "1"}], ["Biến tích lũy s = 0; mỗi vòng cộng thêm i."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int s = 0;\n    for (int i = 1; i <= n; i++)\n        s += i;\n    cout << s;\n    return 0;\n}", "Bien tich luy cong dan tung so trong vong lap la kieu bai toan tong kinh dien.", ["loops", "sum", "for"]],
    ["Bảng cửu chương", "medium", "Doc n. In bang cuu chuong cua n tu 1 den 10, moi dong dinh dang: n x i = ket-qua (co dau cach xung quanh x va =).", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "3", "expected": "3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15\n3 x 6 = 18\n3 x 7 = 21\n3 x 8 = 24\n3 x 9 = 27\n3 x 10 = 30"}], ["Vòng for i = 1..10.", "Chu y dau cach trong chuoi x va =."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    for (int i = 1; i <= 10; i++)\n        cout << n << \" x \" << i << \" = \" << n * i << \"\\n\";\n    return 0;\n}", "Vong lap sinh ra 10 dong co cung cau truc, chi khac gia tri i.", ["loops", "for", "output"]],
    ["Giai thừa", "medium", "Doc n (0 <= n <= 12). In n! dung while.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "5", "expected": "120"}, {"input": "0", "expected": "1"}, {"input": "3", "expected": "6"}, {"input": "12", "expected": "479001600"}], ["Bắt đầu f = 1, nhân dần từ 1 đến n.", "0! bằng 1."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int f = 1, i = 1;\n    while (i <= n) {\n        f *= i;\n        i++;\n    }\n    cout << f;\n    return 0;\n}", "Giai thua la tich lien tiep tu 1 den n; 0! quy uoc bang 1.", ["loops", "while", "factorial"]],
    ["Đếm chữ số với do-while", "medium", "Doc so nguyen khong am n. In ra so chu so cua n. Rieng so 0 co 1 chu so.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "0", "expected": "1"}, {"input": "9", "expected": "1"}, {"input": "42", "expected": "2"}, {"input": "1000", "expected": "4"}], ["do-while đảm bảo thân lặp chạy ít nhất một lần.", "Chia n cho 10 tới khi hết."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    int c = 0;\n    do {\n        c++;\n        n /= 10;\n    } while (n > 0);\n    cout << c;\n    return 0;\n}", "do-while chay than lap truoc khi kiem tra nen so 0 cung duoc tinh 1 chu so.", ["loops", "do-while", "digits"]],
    ["Lọc số bằng continue", "hard", "Doc n. In cac so le tu 1 den n LOAI bo cac so chia het cho 3, moi so mot dong, dung continue.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "15", "expected": "1\n5\n7\n11\n13"}, {"input": "7", "expected": "1\n5\n7"}], ["Bước nhảy 2 để chỉ duyệt số lẻ.", "if (i % 3 == 0) continue;"], "#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    for (int i = 1; i <= n; i += 2) {\n        if (i % 3 == 0)\n            continue;\n        cout << i << \"\\n\";\n    }\n    return 0;\n}", "continue bun qua phan con lai cua vong lap hien tai; buoc nhay 2 giu chi duyet so le.", ["loops", "continue", "for"]],
    ["FizzBuzz", "hard", "Doc n (<= 50). In tu 1 den n, moi gia tri mot dong: chia het 3 in Fizz, chia het 5 in Buzz, chia het ca 2 in FizzBuzz, con lai in chinh no.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "15", "expected": "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz"}], ["Kiểm tra chia hết cho 15 trước.", "Dùng n % 15, n % 3, n % 5."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n;\n    cin >> n;\n    for (int i = 1; i <= n; i++) {\n        if (i % 15 == 0)\n            cout << \"FizzBuzz\";\n        else if (i % 3 == 0)\n            cout << \"Fizz\";\n        else if (i % 5 == 0)\n            cout << \"Buzz\";\n        else\n            cout << i;\n        cout << \"\\n\";\n    }\n    return 0;\n}", "Nhan 15 (boi chung nho nhat cua 3 va 5) phai duoc kiem tra dau tien neu khong FizzBuzz khong bao gio xay ra.", ["loops", "if-else", "modulo", "fizzbuzz"]],
  ]);
  add("08 · Mảng", [
    ["Tổng mảng", "easy", "Doc n (<= 100) roi n so nguyen. In tong cua chung.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "3 1 2 3", "expected": "6"}, {"input": "4 5 5 5 5", "expected": "20"}], ["Mảng cố định int a[100].", "Vòng for cộng dồn."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n, a[100], s = 0;\n    cin >> n;\n    for (int i = 0; i < n; i++) {\n        cin >> a[i];\n        s += a[i];\n    }\n    cout << s;\n    return 0;\n}", "Mang luu nhieu gia tri cung kieu va duyet bang chi so tu 0 den n-1.", ["arrays", "loops", "sum"]],
    ["Số lớn nhất của 5 phần tử", "easy", "Doc 5 so nguyen va in ra so lon nhat.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "1 9 4 7 2", "expected": "9"}, {"input": "-5 -1 -9 -3 -7", "expected": "-1"}], ["Gán max = phần tử đầu.", "Cập nhật khi gặp số lớn hơn."], "#include <iostream>\nusing namespace std;\nint main() {\n    int a[5], mx;\n    for (int i = 0; i < 5; i++)\n        cin >> a[i];\n    mx = a[0];\n    for (int i = 1; i < 5; i++)\n        if (a[i] > mx)\n            mx = a[i];\n    cout << mx;\n    return 0;\n}", "Tim max la kieu duyet so sanh voi gia tri lon nhat tam thoi.", ["arrays", "max", "loops"]],
    ["Đảo ngược mảng", "medium", "Doc n roi n so. In cac so theo thu tu dao nguoc, cach nhau boi dau cach.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "4 1 2 3 4", "expected": "4 3 2 1"}, {"input": "3 7 8 9", "expected": "9 8 7"}], ["Duyệt ngược chỉ số từ n-1 về 0.", "In dấu cách trước các phần tử sau."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n, a[100];\n    cin >> n;\n    for (int i = 0; i < n; i++)\n        cin >> a[i];\n    for (int i = n - 1; i >= 0; i--) {\n        if (i != n - 1)\n            cout << \" \";\n        cout << a[i];\n    }\n    return 0;\n}", "Duyet chi so nguoc de trong tu cuoi len dau ma khong can dao mang.", ["arrays", "reverse", "loops"]],
    ["Tổng ma trận", "medium", "Doc r, c roi r*c so nguyen (ma tran r hang, c cot). In tong tat cac phan tu.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "2 2 1 2 3 4", "expected": "10"}, {"input": "1 3 5 5 5", "expected": "15"}], ["Vòng lặp lồng: hàng rồi cột.", "Hoặc đọc thẳng r*c số vào một biến tổng."], "#include <iostream>\nusing namespace std;\nint main() {\n    int r, c;\n    cin >> r >> c;\n    int m[20][20], s = 0;\n    for (int i = 0; i < r; i++)\n        for (int j = 0; j < c; j++) {\n            cin >> m[i][j];\n            s += m[i][j];\n        }\n    cout << s;\n    return 0;\n}", "Mang 2 chieu dung vong lap long: chi so hang va chi so cot.", ["arrays", "2d", "nested-loops"]],
    ["Đếm số chẵn", "easy", "Doc n roi n so nguyen. In ra co bao nhieu so chan.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "5 1 2 3 4 6", "expected": "3"}, {"input": "3 1 3 5", "expected": "0"}], ["a[i] % 2 == 0.", "Biến đếm tăng khi gặp số chẵn."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n, a[100], c = 0;\n    cin >> n;\n    for (int i = 0; i < n; i++) {\n        cin >> a[i];\n        if (a[i] % 2 == 0)\n            c++;\n    }\n    cout << c;\n    return 0;\n}", "Vua doc vua kiem tra va dem giup chi duyet mang mot lan.", ["arrays", "loops", "count"]],
    ["Tìm phần tử", "medium", "Doc n, roi n so, roi mot gia tri key. In chi so (bat dau tu 0) cua lan xuat hien dau tien, hoac -1 neu khong thay.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "5 4 2 7 7 1 7", "expected": "2"}, {"input": "3 1 2 3 9", "expected": "-1"}], ["Vòng for + if khớp thì in và break.", "Cờ found = false ban đầu."], "#include <iostream>\nusing namespace std;\nint main() {\n    int n, a[100], key;\n    cin >> n;\n    for (int i = 0; i < n; i++)\n        cin >> a[i];\n    cin >> key;\n    int pos = -1;\n    for (int i = 0; i < n; i++)\n        if (a[i] == key) {\n            pos = i;\n            break;\n        }\n    cout << pos;\n    return 0;\n}", "break dung tim kiem ngay khi thay lan dau nen ket qua la chi so dau tien.", ["arrays", "search", "break"]],
  ]);
  add("09 · Struct, Enum, Tham chiếu & Con trỏ", [
    ["Struct Point", "medium", "Doc 4 so nguyen x1 y1 x2 y2 vao mot struct Point. In binh phuong khoang cach (dx*dx + dy*dy).", "#include <iostream>\nusing namespace std;\n\nstruct Point {\n    int x, y;\n};\n", [{"input": "0 0 3 4", "expected": "25"}, {"input": "1 1 1 1", "expected": "0"}, {"input": "-2 -2 4 -2", "expected": "36"}], ["Truy cap thanh vien: p.x.", "dx = x2 - x1."], "#include <iostream>\nusing namespace std;\n\nstruct Point {\n    int x, y;\n};\n\nint main() {\n    Point a, b;\n    cin >> a.x >> a.y >> b.x >> b.y;\n    int dx = b.x - a.x;\n    int dy = b.y - a.y;\n    cout << dx * dx + dy * dy;\n    return 0;\n}", "struct gom nhieu truong lien quan thanh mot kieu moi co the khoi tao va truy cap bang cham.", ["struct", "members"]],
    ["Học sinh với struct", "medium", "Doc ten (mot tu) va diem. In theo dang: <ten> - <loai>. Loai: >=80 A, >=60 B, >=40 C, duoi F.", "#include <iostream>\n#include <string>\nusing namespace std;\n\nstruct Student {\n    string name;\n    int score;\n};\n", [{"input": "Lan 95", "expected": "Lan - A"}, {"input": "Hung 45", "expected": "Hung - C"}, {"input": "Mai 30", "expected": "Mai - F"}], ["Doc struct tung truong.", "if/else if phan loai diem."], "#include <iostream>\n#include <string>\nusing namespace std;\n\nstruct Student {\n    string name;\n    int score;\n};\n\nint main() {\n    Student s;\n    cin >> s.name >> s.score;\n    char grade;\n    if (s.score >= 80) grade = 'A';\n    else if (s.score >= 60) grade = 'B';\n    else if (s.score >= 40) grade = 'C';\n    else grade = 'F';\n    cout << s.name << \" - \" << grade;\n    return 0;\n}", "struct giu du lieu cua mot doi tuong di cung; xep loai ap dung ngay tren thanh vien.", ["struct", "conditions"]],
    ["Đổi số qua tham chiếu", "easy", "Doc a, b. Goi ham swapRefs(int& x, int& y) de dao gia tri roi in ra a va b (cach nhau mot dau cach).", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "3 7", "expected": "7 3"}, {"input": "1 2", "expected": "2 1"}], ["Tham so int& sua truc tiep bien goi.", "Dung bien tam de dao."], "#include <iostream>\nusing namespace std;\n\nvoid swapRefs(int &x, int &y) {\n    int t = x;\n    x = y;\n    y = t;\n}\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    swapRefs(a, b);\n    cout << a << \" \" << b;\n    return 0;\n}", "Reference la biet danh cua bien goi nen moi thay doi trong ham anh huong ngoai main.", ["references", "swap", "function"]],
    ["Đổi số qua con trỏ", "medium", "Doc a, b. Goi ham swapPtr(int* x, int* y) dung dia chi de dao gia tri, roi in a va b dao nguoc.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "4 9", "expected": "9 4"}, {"input": "0 -1", "expected": "-1 0"}], ["Gui &a va &b.", "Truy gia tri qua *x."], "#include <iostream>\nusing namespace std;\n\nvoid swapPtr(int *x, int *y) {\n    int t = *x;\n    *x = *y;\n    *y = t;\n}\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    swapPtr(&a, &b);\n    cout << a << \" \" << b;\n    return 0;\n}", "Con tro luu dia chi; *x doc/ghi gia tri tai dia chi do.", ["pointers", "swap", "memory"]],
    ["Thứ trong tuần với enum", "medium", "Khai bao enum Weekday { Mon = 1, Tue, Wed, Thu, Fri, Sat, Sun };. Doc so 1-7 va in ten thu; ngoai khoang do in Invalid.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "1", "expected": "Mon"}, {"input": "7", "expected": "Sun"}, {"input": "9", "expected": "Invalid"}], ["Enum tự tăng giá trị từ giá trị đầu.", " mảng tên tra cứu theo chỉ số hoặc switch."], "#include <iostream>\nusing namespace std;\n\nenum Weekday { Mon = 1, Tue, Wed, Thu, Fri, Sat, Sun };\n\nint main() {\n    int d;\n    cin >> d;\n    const char* names[] = {\"?\", \"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\"};\n    if (d >= Mon && d <= Sun)\n        cout << names[d];\n    else\n        cout << \"Invalid\";\n    return 0;\n}", "enum tao tap hop hang so co ten va thuc chat la so nguyen nen dung lam chi so duoc.", ["enum", "constants", "arrays"]],
    ["Thủ khoa", "hard", "Doc n (<= 50) roi n cap <ten diem>. In ten va diem cua nguoi co diem cao nhat, cach nhau mot dau cach.", "#include <iostream>\n#include <string>\nusing namespace std;\n\nstruct Student {\n    string name;\n    int score;\n};\n", [{"input": "3\nTung 95\nLan 88\nHa 90", "expected": "Tung 95"}, {"input": "2\nAn 50\nBinh 51", "expected": "Binh 51"}], ["Mảng struct Student a[50].", "Ghi lại chỉ số của điểm lớn nhất."], "#include <iostream>\n#include <string>\nusing namespace std;\n\nstruct Student {\n    string name;\n    int score;\n};\n\nint main() {\n    int n;\n    cin >> n;\n    Student a[50];\n    for (int i = 0; i < n; i++)\n        cin >> a[i].name >> a[i].score;\n    int best = 0;\n    for (int i = 1; i < n; i++)\n        if (a[i].score > a[best].score)\n            best = i;\n    cout << a[best].name << \" \" << a[best].score;\n    return 0;\n}", "Ket hop struct va vong lap de tim phan tu max theo mot truong.", ["struct", "arrays", "max"]],
  ]);
  add("10 · Hàm (Functions)", [
    ["Hàm đầu tiên", "easy", "Viet ham void greet() in ra: Hello from function! Roi goi tu main.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "", "expected": "Hello from function!"}], ["Ham void khong tra gia tri.", "Phai dinh nghia truoc khi goi."], "#include <iostream>\nusing namespace std;\n\nvoid greet() {\n    cout << \"Hello from function!\";\n}\n\nint main() {\n    greet();\n    return 0;\n}", "Ham dong goi mot kho lenh co the tai su dung; void nghia la khong tra gia tri.", ["functions", "void"]],
    ["Hàm có tham số", "easy", "Viet ham int sum(int a, int b). Doc hai so, in sum cua chung.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "4 6", "expected": "10"}, {"input": "-2 2", "expected": "0"}], ["Kieu tra ve dat truoc ten ham.", "return a + b."], "#include <iostream>\nusing namespace std;\n\nint sum(int a, int b) {\n    return a + b;\n}\n\nint main() {\n    int x, y;\n    cin >> x >> y;\n    cout << sum(x, y);\n    return 0;\n}", "Tham so nhan gia tri tu noi goi; return gui ket qua nguoc lai.", ["functions", "parameters", "return"]],
    ["Tham số mặc định", "medium", "Viet ham printLine(char c = '*', int n = 10) in n ky tu c. Doc k; main goi printLine('=', k) xuong dong roi printLine().", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "5", "expected": "=====\n**********"}, {"input": "3", "expected": "===\n**********"}], ["Tham so mac dinh dat o cuoi danh sach.", "Tron chuoi bang string(n, c)."], "#include <iostream>\n#include <string>\nusing namespace std;\n\nvoid printLine(char c = '*', int n = 10) {\n    cout << string(n, c);\n}\n\nint main() {\n    int k;\n    cin >> k;\n    printLine('=', k);\n    cout << \"\\n\";\n    printLine();\n    return 0;\n}", "Khi goi khong truyen, tham so mac dinh duoc dung nen printLine() in 10 dau *.", ["functions", "default-arguments"]],
    ["Hàm trả bool", "easy", "Viet ham bool isEven(int n). Doc n va in Even/Odd dua vao ham.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "8", "expected": "Even"}, {"input": "7", "expected": "Odd"}], ["return n % 2 == 0.", "bool dung duoc trong dieu kien."], "#include <iostream>\nusing namespace std;\n\nbool isEven(int n) {\n    return n % 2 == 0;\n}\n\nint main() {\n    int n;\n    cin >> n;\n    cout << (isEven(n) ? \"Even\" : \"Odd\");\n    return 0;\n}", "Ham kiem tra tra bool giup ten goi mo hon hon so voi toan so trong main.", ["functions", "return", "boolean"]],
    ["Hàm chồng nhau (overload)", "medium", "Viet printMax(int,int) va printMax(int,int,int) - moi ham in gia tri lon nhat ra mot dong. Doc ba so a b c; main goi printMax(a, b) roi printMax(a, b, c).", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "1 9 4", "expected": "9\n9"}, {"input": "5 2 7", "expected": "5\n7"}, {"input": "3 3 3", "expected": "3\n3"}], ["Cung ten khac danh sach tham so.", "Ham khac so luong tham so."], "#include <iostream>\nusing namespace std;\n\nvoid printMax(int a, int b) {\n    cout << (a > b ? a : b) << \"\\n\";\n}\n\nvoid printMax(int a, int b, int c) {\n    int m = a;\n    if (b > m) m = b;\n    if (c > m) m = c;\n    cout << m;\n}\n\nint main() {\n    int a, b, c;\n    cin >> a >> b >> c;\n    printMax(a, b);\n    printMax(a, b, c);\n    return 0;\n}", "Overloading: cung ten ham nhung khac chu ky tham so va compiler tu chon ban phu hop.", ["functions", "overloading"]],
    ["Đệ quy", "hard", "Viet ham int fact(int n) dung de quy. Doc n (<= 12) va in n!.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "5", "expected": "120"}, {"input": "0", "expected": "1"}, {"input": "10", "expected": "3628800"}], ["Điều kiện dừng: n <= 1 trả về 1.", "fact(n) = n * fact(n - 1)."], "#include <iostream>\nusing namespace std;\n\nint fact(int n) {\n    if (n <= 1)\n        return 1;\n    return n * fact(n - 1);\n}\n\nint main() {\n    int n;\n    cin >> n;\n    cout << fact(n);\n    return 0;\n}", "De quy goi lai chinh no voi bai toan nho hon; Dieu kien dung ngan goi vo tan.", ["functions", "recursion"]],
    ["Lambda cơ bản", "medium", "Doc a, b. Viet lambda add va mul, in ket qua dang: <tong> <tich>.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "5 7", "expected": "12 35"}, {"input": "2 3", "expected": "5 6"}], ["[](){...} la dinh dang lambda.", "auto f = [](int x, int y){ return x + y; };"], "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    auto add = [](int x, int y) { return x + y; };\n    auto mul = [](int x, int y) { return x * y; };\n    cout << add(a, b) << \" \" << mul(a, b);\n    return 0;\n}", "Lambda la ham viet inline, thuong luu trong auto va dung ngay cho bieu thuc ngan.", ["functions", "lambda"]],
  ]);
  add("11 · OOP & Kế thừa", [
    ["Lớp Dog", "easy", "Tao lop Dog co thanh vien private string name va cong khai speak() in '<ten> says Woof!'. Doc ten va cho no noi.", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "Rex", "expected": "Rex says Woof!"}, {"input": "Kuta", "expected": "Kuta says Woof!"}], ["private chan truy cap truc tiep.", "Constructor khoi tao name."], "#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Dog {\nprivate:\n    string name;\npublic:\n    Dog(string n) : name(n) {}\n    void speak() {\n        cout << name << \" says Woof!\";\n    }\n};\n\nint main() {\n    string n;\n    cin >> n;\n    Dog d(n);\n    d.speak();\n    return 0;\n}", "Encapsulation: giu lieu rieng tu, chi cong khai hanh vi an toan.", ["oop", "class", "encapsulation"]],
    ["Constructor Point", "medium", "Lop Point co constructor Point(int x, int y). Doc x1 y1 x2 y2, tao hai Point va in binh phuong khoang cach giua chung.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "0 0 3 4", "expected": "25"}, {"input": "1 2 4 6", "expected": "25"}, {"input": "5 5 5 5", "expected": "0"}], ["Danh sach khoi tao : x(a), y(b).", "dx*dx + dy*dy."], "#include <iostream>\nusing namespace std;\n\nclass Point {\n    int x, y;\npublic:\n    Point(int a, int b) : x(a), y(b) {}\n    int dxTo(const Point& o) const { return x - o.x; }\n    int dyTo(const Point& o) const { return y - o.y; }\n};\n\nint main() {\n    int x1, y1, x2, y2;\n    cin >> x1 >> y1 >> x2 >> y2;\n    Point p(x1, y1), q(x2, y2);\n    int dx = p.dxTo(q), dy = p.dyTo(q);\n    cout << dx * dx + dy * dy;\n    return 0;\n}", "Constructor bao dam doi tuong sinh ra da co du lieu hop le.", ["oop", "constructor", "class"]],
    ["Hộp mật khẩu", "medium", "Lop Secret co bien thanh vien private int value = 0, cac ham setValue va getValue. Doc n, goi setValue(n), in getValue() * 2.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "7", "expected": "14"}, {"input": "0", "expected": "0"}, {"input": "-3", "expected": "-6"}], ["getter/seter la quy uoc encapsulation.", "value tu 0 thanh n sau setValue."], "#include <iostream>\nusing namespace std;\n\nclass Secret {\nprivate:\n    int value = 0;\npublic:\n    void setValue(int v) { value = v; }\n    int getValue() const { return value; }\n};\n\nint main() {\n    int n;\n    cin >> n;\n    Secret s;\n    s.setValue(n);\n    cout << s.getValue() * 2;\n    return 0;\n}", "Getter/setter kiem soat cach du lieu bi thay doi thay vi de public.", ["oop", "encapsulation", "class"]],
    ["Kế thừa Animal", "medium", "Lop Animal co void eat() in Animal eats. Lop Cat ke thua Animal va co meow() in Cat says Meow. main goi ca hai, moi ket qua mot dong.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "", "expected": "Animal eats\nCat says Meow"}], ["class Cat : public Animal.", "Ham ke thua tu dong co cua bo."], "#include <iostream>\nusing namespace std;\n\nclass Animal {\npublic:\n    void eat() {\n        cout << \"Animal eats\\n\";\n    }\n};\n\nclass Cat : public Animal {\npublic:\n    void meow() {\n        cout << \"Cat says Meow\";\n    }\n};\n\nint main() {\n    Cat c;\n    c.eat();\n    c.meow();\n    return 0;\n}", "Ke thua public tai lai hanh vi cua lop cha va co the mo rong hanh vi moi.", ["oop", "inheritance", "class"]],
    ["Đa hình với virtual", "hard", "Lop co so Shape co virtual int area() const. Lop Square(int) va Rect(int,int) ghi de area. Doc n; tao Square(n) va Rect(n, n+1); goi area qua tham chieu Shape& va in hai gia tri tren hai dong.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "3", "expected": "9\n12"}, {"input": "4", "expected": "16\n20"}], ["override khi ghi de virtual.", "Goi qua Shape& de thay da hinh."], "#include <iostream>\nusing namespace std;\n\nclass Shape {\npublic:\n    virtual int area() const { return 0; }\n};\n\nclass Square : public Shape {\n    int s;\npublic:\n    Square(int x) : s(x) {}\n    int area() const override { return s * s; }\n};\n\nclass Rect : public Shape {\n    int w, h;\npublic:\n    Rect(int a, int b) : w(a), h(b) {}\n    int area() const override { return w * h; }\n};\n\nint main() {\n    int n;\n    cin >> n;\n    Square sq(n);\n    Rect rc(n, n + 1);\n    const Shape& a = sq;\n    const Shape& b = rc;\n    cout << a.area() << \"\\n\" << b.area();\n    return 0;\n}", "Ham virtual duoc phan quyet luc chay theo kieu that cua doi tuong - cot loi cua polymorphism.", ["oop", "polymorphism", "virtual", "inheritance"]],
    ["Biến static đếm đối tượng", "medium", "Lop Counter co static int total bat dau tu 0 va constructor tang total. Doc n; tao n doi tuong trong vong lap; in Counter::total.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "3", "expected": "3"}, {"input": "5", "expected": "5"}, {"input": "1", "expected": "1"}], ["static thuoc ve lop, khong phai tung doi tuong.", "Dinh nghia ben ngoai: int Counter::total = 0;"], "#include <iostream>\nusing namespace std;\n\nclass Counter {\npublic:\n    static int total;\n    Counter() { total++; }\n};\n\nint Counter::total = 0;\n\nint main() {\n    int n;\n    cin >> n;\n    for (int i = 0; i < n; i++) {\n        Counter c;\n    }\n    cout << Counter::total;\n    return 0;\n}", "Bien static chia se gia tri giua moi doi tuong cung lop nen dung dem so luong.", ["oop", "static", "class"]],
  ]);
  add("12 · Templates, File & Xử lý lỗi", [
    ["Template max", "easy", "Viet template<typename T> T maxT(T a, T b). Doc hai int va hai double, in max cua tung cap; so thap phan in 1 chu so.", "#include <iostream>\n#include <iomanip>\nusing namespace std;\n", [{"input": "3 5 3.4 2.8", "expected": "5\n3.4"}, {"input": "9 2 1.5 2.5", "expected": "9\n2.5"}], ["Mot template dung cho nhieu kieu.", "fixed + setprecision(1) cho double."], "#include <iostream>\n#include <iomanip>\nusing namespace std;\n\ntemplate<typename T>\nT maxT(T a, T b) {\n    return a > b ? a : b;\n}\n\nint main() {\n    int a, b;\n    double x, y;\n    cin >> a >> b >> x >> y;\n    cout << maxT(a, b) << \"\\n\";\n    cout << fixed << setprecision(1) << maxT(x, y);\n    return 0;\n}", "Template sinh ra ban copy cua ham cho tung kieu duoc goi (int, double).", ["templates", "function-template"]],
    ["Lớp template Box", "medium", "Viet template<class T> class Box luu gia tri va co get(). Doc mot so va mot tu; tao Box<int> va Box<string>; in so*2 tren mot dong va tu + '!' o dong sau.", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "5 hello", "expected": "10\nhello!"}, {"input": "7 C++", "expected": "14\nC++!"}], ["Template cho lop cung nhu ham.", "Khai bao Box<int> bi(n)."], "#include <iostream>\n#include <string>\nusing namespace std;\n\ntemplate<class T>\nclass Box {\n    T val;\npublic:\n    Box(T v) : val(v) {}\n    T get() const { return val; }\n};\n\nint main() {\n    int n;\n    string s;\n    cin >> n >> s;\n    Box<int> bi(n);\n    Box<string> bs(s);\n    cout << bi.get() * 2 << \"\\n\" << bs.get() << \"!\";\n    return 0;\n}", "Class template viet lop mot lan dung cho moi kieu du lieu.", ["templates", "class-template"]],
    ["Bắt lỗi chia cho 0", "medium", "Doc a, b. Dung try/catch: neu b == 0 nem ra chuoi \"Error: divide by zero\" va bat de in ra; nguoc lai in thuong nguyen a / b.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "10 2", "expected": "5"}, {"input": "6 0", "expected": "Error: divide by zero"}, {"input": "0 5", "expected": "0"}], ["throw nem mot gia tri.", "catch (const char* e) bat dung loai."], "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    try {\n        if (b == 0)\n            throw \"Error: divide by zero\";\n        cout << a / b;\n    } catch (const char* e) {\n        cout << e;\n    }\n    return 0;\n}", "try bao vung lenh nguy hiem; throw chuyen loi toi catch gan nhat cung kieu.", ["exceptions", "error-handling", "try-catch"]],
    ["Nhiều kiểu catch", "hard", "Doc n. Trong try: neu n < 0 nem so nguyen 1; neu n == 0 nem so thuc 2.0; nguoc lai in n*n. catch(int) in Negative, catch(double) in Zero.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "-4", "expected": "Negative"}, {"input": "0", "expected": "Zero"}, {"input": "3", "expected": "9"}], ["Mỗi catch bat dung mot kieu.", "Thu tu catch khong bat buoc cung kieu."], "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    try {\n        if (n < 0)\n            throw 1;\n        if (n == 0)\n            throw 2.0;\n        cout << n * n;\n    } catch (int e) {\n        cout << \"Negative\";\n    } catch (double e) {\n        cout << \"Zero\";\n    }\n    return 0;\n}", "Kieu cua gia tri throw quyet dinh catch nao chay - co the dinh tuyen loi theo loai.", ["exceptions", "error-handling"]],
    ["Exception tùy chỉnh", "hard", "Viet lop AgeError ke thua exception va ghi de what() tra ve \"Invalid age\". Doc tuoi: ngoai khoang 0-120 thi nem va bat AgeError, nguoc lai in chinh tuoi.", "#include <iostream>\n#include <exception>\nusing namespace std;\n", [{"input": "25", "expected": "25"}, {"input": "-3", "expected": "Invalid age"}, {"input": "130", "expected": "Invalid age"}], ["Ke thua std::exception.", "what() phai la const noexcept override."], "#include <iostream>\n#include <exception>\nusing namespace std;\n\nclass AgeError : public exception {\npublic:\n    const char* what() const noexcept override {\n        return \"Invalid age\";\n    }\n};\n\nint main() {\n    int age;\n    cin >> age;\n    try {\n        if (age < 0 || age > 120)\n            throw AgeError();\n        cout << age;\n    } catch (const AgeError& e) {\n        cout << e.what();\n    }\n    return 0;\n}", "Lop exception rieng cho goi loi co ten va thong diep rieng, bat bang catch theo kieu.", ["exceptions", "inheritance", "error-handling"]],
    ["Template đếm phần tử", "hard", "Viet template ham countIn(const vector<T>& v, T x) dung std::count. Doc n, n so nguyen, roi mot gia tri key. In ra so lan key xuat hien.", "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n", [{"input": "6 2 7 2 9 2 4 2", "expected": "3"}, {"input": "3 1 2 3 9", "expected": "0"}], ["Dung std::count(v.begin(), v.end(), x).", "Template ham cho vector moi kieu."], "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\ntemplate<class T>\nint countIn(const vector<T> &v, T x) {\n    return (int)count(v.begin(), v.end(), x);\n}\n\nint main() {\n    int n;\n    cin >> n;\n    vector<int> v(n);\n    for (int &x : v)\n        cin >> x;\n    int key;\n    cin >> key;\n    cout << countIn(v, key);\n    return 0;\n}", "Ket hop template voi STL algorithm: mot ham dem dung duoc cho vector bat ky kieu nao.", ["templates", "algorithm", "vector"]],
  ]);
  add("13 · STL & Containers", [
    ["Vector tổng", "easy", "Doc n roi n so. Luu vao vector va in tong.", "#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "4 1 2 3 4", "expected": "10"}, {"input": "2 -5 5", "expected": "0"}], ["vector<int> v(n).", "Vong for range-based: for (int x : v)."], "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    vector<int> v(n);\n    for (int &x : v)\n        cin >> x;\n    int s = 0;\n    for (int x : v)\n        s += x;\n    cout << s;\n    return 0;\n}", "Vector tu quan ly bo nho hon mang co dinh va ho tro duyet bang range-for.", ["vector", "stl", "sum"]],
    ["Top 3 lớn nhất", "medium", "Doc n (>= 3) roi n so. Sap xep giam dan va in 3 so dau, cach nhau boi dau cach.", "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n", [{"input": "5 4 2 9 7 5", "expected": "9 7 5"}, {"input": "3 1 2 3", "expected": "3 2 1"}], ["sort(v.begin(), v.end(), greater<int>()).", "In v[0], v[1], v[2]."], "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    vector<int> v(n);\n    for (int &x : v)\n        cin >> x;\n    sort(v.begin(), v.end(), greater<int>());\n    cout << v[0] << \" \" << v[1] << \" \" << v[2];\n    return 0;\n}", "sort voi comparator greater<> dao thu tu giam dan de lay nhanh top.", ["vector", "sort", "stl", "algorithm"]],
    ["Mô phỏng Stack", "medium", "Dong dau la m so lenh. Cac lenh: 'push x' day x vao stack, 'pop' lay ra mot phan tu (bo qua neu rong), 'top' in dinh stack hoac in empty neu rong. Moi ket qua top mot dong.", "#include <iostream>\n#include <stack>\n#include <string>\nusing namespace std;\n", [{"input": "5 push 5 push 9 top pop top", "expected": "9\n5"}, {"input": "3 top push 4 top", "expected": "empty\n4"}, {"input": "5 push 1 push 2 pop pop top", "expected": "empty"}], ["stack<int> st; day: st.push(x).", "Rong: st.empty()."], "#include <iostream>\n#include <stack>\n#include <string>\nusing namespace std;\n\nint main() {\n    int m;\n    cin >> m;\n    stack<int> st;\n    for (int i = 0; i < m; i++) {\n        string op;\n        cin >> op;\n        if (op == \"push\") {\n            int x;\n            cin >> x;\n            st.push(x);\n        } else if (op == \"pop\") {\n            if (!st.empty())\n                st.pop();\n        } else {\n            if (st.empty())\n                cout << \"empty\";\n            else\n                cout << st.top();\n            cout << \"\\n\";\n        }\n    }\n    return 0;\n}", "Stack LIFO: chi thao tac voi dinh nen top/pop deu O(1).", ["stack", "stl", "lifo"]],
    ["Trò chơi vòng tròn (Queue)", "hard", "n nguoi danh so 1..n dung thanh hang doi. Lap di lap lai: quay k-1 nguoi dau ra sau roi loai mot nguoi cho toi khi con 1. Doc n va k, in so thu tu nguoi song sot.", "#include <iostream>\n#include <queue>\nusing namespace std;\n", [{"input": "5 2", "expected": "3"}, {"input": "6 2", "expected": "5"}, {"input": "7 3", "expected": "4"}], ["queue<int> q day 1..n.", "Moi vong: quay (k-1) lan push front roi pop, sau do pop nua."], "#include <iostream>\n#include <queue>\nusing namespace std;\n\nint main() {\n    int n, k;\n    cin >> n >> k;\n    queue<int> q;\n    for (int i = 1; i <= n; i++)\n        q.push(i);\n    while (q.size() > 1) {\n        for (int s = 1; s < k; s++) {\n            q.push(q.front());\n            q.pop();\n        }\n        q.pop();\n    }\n    cout << q.front();\n    return 0;\n}", "Hang doi xoay vong cho phep mo phong pheu loai Josephus ma khong can chi so.", ["queue", "stl", "fifo"]],
    ["Set loại trùng", "medium", "Doc n roi n so nguyen. Dung set de loai trung va in ra so gia tri khac nhau.", "#include <iostream>\n#include <set>\nusing namespace std;\n", [{"input": "6 1 2 2 3 1 2", "expected": "3"}, {"input": "3 5 5 5", "expected": "1"}], ["set tu loai bo phan tu trung lap.", "size() dem phan tu khac nhau."], "#include <iostream>\n#include <set>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    set<int> s;\n    for (int i = 0; i < n; i++) {\n        int x;\n        cin >> x;\n        s.insert(x);\n    }\n    cout << s.size();\n    return 0;\n}", "Set chi luu mot lan moi gia tri nen so phan tu chinh la so gia tri distinct.", ["set", "stl", "unique"]],
    ["Bảng điểm với map", "medium", "Doc n roi n cap <ten diem>. Dung map de luu va in ra tung cap theo thu tu chu cai cua ten, moi dong dang: <ten> <diem>.", "#include <iostream>\n#include <map>\n#include <string>\nusing namespace std;\n", [{"input": "2\nHung 8\nAn 9", "expected": "An 9\nHung 8"}, {"input": "1\nZ 5", "expected": "Z 5"}], ["map<string,int> tu sap xep theo khoa.", "Duyet: for (auto& p : mp)."], "#include <iostream>\n#include <map>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    map<string, int> scores;\n    for (int i = 0; i < n; i++) {\n        string name;\n        int score;\n        cin >> name >> score;\n        scores[name] = score;\n    }\n    for (const auto &p : scores)\n        cout << p.first << \" \" << p.second << \"\\n\";\n    return 0;\n}", "map giu cap khoa-gia tri va duyet theo khoa tang dan nen ten tu xep theo chu cai.", ["map", "stl", "pairs"]],
  ]);
  add("14 · Dự án & Chứng chỉ", [
    ["Dự án máy tính bỏ túi", "medium", "Doc a, toan tu (+, -, *, /) va b. In ket qua la so nguyen. Chia cho 0 in Error. Dung switch.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "6 / 2", "expected": "3"}, {"input": "5 * 3", "expected": "15"}, {"input": "8 / 0", "expected": "Error"}, {"input": "9 - 4", "expected": "5"}, {"input": "2 + 3", "expected": "5"}], ["Doc char op giua hai so.", "switch tren bien char."], "#include <iostream>\nusing namespace std;\n\nint main() {\n    int a, b;\n    char op;\n    cin >> a >> op >> b;\n    switch (op) {\n        case '+': cout << a + b; break;\n        case '-': cout << a - b; break;\n        case '*': cout << a * b; break;\n        case '/':\n            if (b == 0)\n                cout << \"Error\";\n            else\n                cout << a / b;\n            break;\n        default: cout << \"Error\";\n    }\n    return 0;\n}", "Du an nho ket hop input, switch va kiem tra loi - dung toan bo ky nang nen tang.", ["project", "switch", "conditions"]],
    ["Dự án sổ điểm", "hard", "Doc n roi n cap <ten diem (0-10)>. In dong dau la Top: <ten thu khoa>, dong thu hai Pass: <so nguoi diem >= 5>.", "#include <iostream>\n#include <string>\nusing namespace std;\n", [{"input": "3\nLan 8\nTung 9\nHa 4", "expected": "Top: Tung\nPass: 2"}, {"input": "1\nAn 3", "expected": "Top: An\nPass: 0"}], ["Mang song song hoac struct.", "Dem pass khi doc, giat max ten thu khoa."], "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    string top;\n    int topScore = -1, pass = 0;\n    for (int i = 0; i < n; i++) {\n        string name;\n        int score;\n        cin >> name >> score;\n        if (score > topScore) {\n            topScore = score;\n            top = name;\n        }\n        if (score >= 5)\n            pass++;\n    }\n    cout << \"Top: \" << top << \"\\nPass: \" << pass;\n    return 0;\n}", "Duyet mot lan vua tim thu khoa vua dem dat - ky nang xu ly du lieu co ban.", ["project", "loops", "max", "count"]],
    ["Dự án sàng số nguyên tố", "hard", "Doc n (<= 100). In tat ca so nguyen to tu 2 den n, moi so mot dong.", "#include <iostream>\nusing namespace std;\n", [{"input": "20", "expected": "2\n3\n5\n7\n11\n13\n17\n19"}, {"input": "2", "expected": "2"}, {"input": "1", "expected": ""}], ["Ham kiem tra chia het toi can(n).", "Hoac mang danh dau sieve."], "#include <iostream>\nusing namespace std;\n\nbool prime(int x) {\n    if (x < 2)\n        return false;\n    for (int i = 2; i <= x / i; i++)\n        if (x % i == 0)\n            return false;\n    return true;\n}\n\nint main() {\n    int n;\n    cin >> n;\n    for (int i = 2; i <= n; i++)\n        if (prime(i))\n            cout << i << \"\\n\";\n    return 0;\n}", "Ket hop ham kiem tra va vong lap; chi can kiem uoc toi can(n).", ["project", "prime", "functions", "loops"]],
    ["Dự án menu xử lý", "hard", "Doc cac lenh cho den het. Moi lenh dang: add x y / sub x y / mul x y / quit. Lenh tinh in ket qua tren mot dong; quit ket thuc (khong in).", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "add 2 3\nmul 4 5\nquit", "expected": "5\n20"}, {"input": "sub 10 4\nquit", "expected": "6"}], ["Doc string op trong khi (cin >> op).", "if/else theo ten lenh."], "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string op;\n    while (cin >> op && op != \"quit\") {\n        int x, y;\n        cin >> x >> y;\n        if (op == \"add\")\n            cout << x + y << \"\\n\";\n        else if (op == \"sub\")\n            cout << x - y << \"\\n\";\n        else if (op == \"mul\")\n            cout << x * y << \"\\n\";\n    }\n    return 0;\n}", "Vong lap doc lenh den het input la mo hinh menu don gian cua CLI tool.", ["project", "loops", "strings", "input"]],
    ["Dự án hồ sơ sinh viên", "hard", "Doc n roi n cap <ten toan ly hoa (diem 0-100)>. Voi moi sinh vien in: <ten> <tb> <loai> (tb la trung binh nguyen, lam tron xuong; loai: >=90 A, >=70 B, >=50 C, duoi F).", "#include <iostream>\n#include <string>\nusing namespace std;\n\nstruct Student {\n    string name;\n    int m, p, c;\n};\n", [{"input": "2\nLan 90 80 85\nHung 40 50 60", "expected": "Lan 85 B\nHung 50 C"}, {"input": "1\nAn 49 49 49", "expected": "An 49 F"}], ["(m + p + c) / 3 la chia nguyen.", "Ham phan loai rieng."], "#include <iostream>\n#include <string>\nusing namespace std;\n\nstruct Student {\n    string name;\n    int m, p, c;\n};\n\nint avg(const Student &s) {\n    return (s.m + s.p + s.c) / 3;\n}\n\nchar grade(int a) {\n    if (a >= 90) return 'A';\n    if (a >= 70) return 'B';\n    if (a >= 50) return 'C';\n    return 'F';\n}\n\nint main() {\n    int n;\n    cin >> n;\n    for (int i = 0; i < n; i++) {\n        Student s;\n        cin >> s.name >> s.m >> s.p >> s.c;\n        cout << s.name << \" \" << avg(s) << \" \" << grade(avg(s)) << \"\\n\";\n    }\n    return 0;\n}", "Chia chuong trinh thanh struct va ham nho - cach to chuc mot du an C++ thang bang.", ["project", "struct", "functions"]],
  ]);
  add("15 · How-To & Tra cứu thư viện", [
    ["Đảo ngược chuỗi", "easy", "Doc mot tu va in ra nguoc lai, dung std::reverse.", "#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "abc", "expected": "cba"}, {"input": "C++", "expected": "++C"}, {"input": "a", "expected": "a"}], ["reverse(s.begin(), s.end()) trong <algorithm>."], "#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    string s;\n    cin >> s;\n    reverse(s.begin(), s.end());\n    cout << s;\n    return 0;\n}", "Thu vien algorithm cung cap thao tac dao chuoi truc tiep tren iterator.", ["strings", "reverse", "algorithm", "how-to"]],
    ["Cộng số lớn", "medium", "Doc hai chuoi so, dung stoll va to_string de in ra tong cua chung.", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "12 30", "expected": "42"}, {"input": "1000000000 1000000000", "expected": "2000000000"}, {"input": "7 8", "expected": "15"}], ["stoll chuyen string sang long long.", "to_string chuyen nguoc lai."], "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string a, b;\n    cin >> a >> b;\n    long long sum = stoll(a) + stoll(b);\n    cout << to_string(sum);\n    return 0;\n}", "Ham chuyen doi string/số giup xu ly du lieu dang chuoi tu file hay input.", ["strings", "conversion", "to_string", "how-to"]],
    ["Đếm ký tự", "easy", "Doc mot tu va dem so lan ky tu 'a' xuat hien, dung std::count.", "#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "banana", "expected": "3"}, {"input": "xyz", "expected": "0"}, {"input": "aaa", "expected": "3"}], ["count(s.begin(), s.end(), 'a')."], "#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    string s;\n    cin >> s;\n    cout << count(s.begin(), s.end(), 'a');\n    return 0;\n}", "std::count dem so lan gia tri xuat hien trong mot khoang iterator.", ["algorithm", "count", "strings", "how-to"]],
    ["Tìm trong vector", "medium", "Doc n roi n so, tiep den key. Dung std::find: neu thay in Found at <vi-tri-1>, nguoc lai in Not found.", "#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "5 4 2 7 7 1 7", "expected": "Found at 3"}, {"input": "3 1 2 3 9", "expected": "Not found"}], ["find tra ve iterator.", "it - v.begin() + 1 cho vi tri dem tu 1."], "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    vector<int> v(n);\n    for (int &x : v)\n        cin >> x;\n    int key;\n    cin >> key;\n    auto it = find(v.begin(), v.end(), key);\n    if (it != v.end())\n        cout << \"Found at \" << (it - v.begin() + 1);\n    else\n        cout << \"Not found\";\n    return 0;\n}", "find dung khi chi can biet co/khong va vi tri; tra ve end() neu khong thay.", ["algorithm", "find", "vector", "how-to"]],
    ["Max với max_element", "easy", "Doc n roi n so. Dung max_element de in gia tri lon nhat.", "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n", [{"input": "4 3 9 1 7", "expected": "9"}, {"input": "3 -5 -1 -9", "expected": "-1"}], ["*max_element(v.begin(), v.end())."], "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    vector<int> v(n);\n    for (int &x : v)\n        cin >> x;\n    cout << *max_element(v.begin(), v.end());\n    return 0;\n}", "max_element tra iterator toi phan tu lon nhat; dau * lay gia tri.", ["algorithm", "max", "how-to", "vector"]],
    ["std::swap", "easy", "Doc hai so va in ra chung dao nguoc, dung std::swap.", "#include <iostream>\n#include <utility>\nusing namespace std;\n", [{"input": "3 7", "expected": "7 3"}, {"input": "2 1", "expected": "1 2"}], ["swap(a, b) trong <utility>."], "#include <iostream>\n#include <utility>\nusing namespace std;\n\nint main() {\n    int a, b;\n    cin >> a >> b;\n    swap(a, b);\n    cout << a << \" \" << b;\n    return 0;\n}", "Thu vien chuan co san swap - khong can tu viet bien tam.", ["swap", "utility", "how-to"]],
  ]);
  add("16 · Thực hành tổng hợp", [
    ["Chuỗi đối xứng", "medium", "Doc mot tu. In Yes neu la palindrome (doc nguoc van nhu nhau), nguoc lai No.", "#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "madam", "expected": "Yes"}, {"input": "abc", "expected": "No"}, {"input": "a", "expected": "Yes"}, {"input": "noon", "expected": "Yes"}], ["Tao ban copy roi reverse.", "So sanh bang ==."], "#include <iostream>\n#include <string>\n#include <algorithm>\nusing namespace std;\n\nint main() {\n    string s;\n    cin >> s;\n    string t = s;\n    reverse(t.begin(), t.end());\n    cout << (s == t ? \"Yes\" : \"No\");\n    return 0;\n}", "Dao ban sao va so sanh la cach kiem tra palindrome don gian nhat.", ["strings", "palindrome", "practice"]],
    ["Đếm nguyên âm", "medium", "Doc mot dong. Dem so nguyen am (a, e, i, o, u - khong phan biet hoa thuong) va in ket qua.", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "Hello World", "expected": "3"}, {"input": "AEIOU aeiou", "expected": "10"}, {"input": "xyz", "expected": "0"}], ["getline lay ca dong.", "if / strfind trong chuoi \"aeiouAEIOU\"."], "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string line;\n    getline(cin, line);\n    string vw = \"aeiouAEIOU\";\n    int c = 0;\n    for (char ch : line)\n        if (vw.find(ch) != string::npos)\n            c++;\n    cout << c;\n    return 0;\n}", "find != npos la cach nhanh de hoi 'ky tu co thuoc tap nao'.", ["strings", "loops", "count", "practice"]],
    ["Đảo thứ tự từ", "hard", "Doc mot dong gom cac tu cach nhau boi khoang trang. In cac tu theo thu tu dao nguoc, cach nhau mot dau cach.", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "hello world", "expected": "world hello"}, {"input": "a b c d", "expected": "d c b a"}, {"input": "one", "expected": "one"}], ["Dua tung tu vao vector<string>.", "Duyet vector nguoc."], "#include <iostream>\n#include <string>\n#include <vector>\nusing namespace std;\n\nint main() {\n    string w;\n    vector<string> ws;\n    while (cin >> w)\n        ws.push_back(w);\n    for (int i = (int)ws.size() - 1; i >= 0; i--) {\n        if (i != (int)ws.size() - 1)\n            cout << \" \";\n        cout << ws[i];\n    }\n    return 0;\n}", "Doc het input vao vector roi duyet nguoc - khuon mau xu ly dong tu nhieu lan.", ["strings", "vector", "reverse", "practice"]],
    ["Dãy Fibonacci", "medium", "Doc n (<= 20). In n so Fibonacci dau (bat dau 0, 1), moi so mot dong.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "7", "expected": "0\n1\n1\n2\n3\n5\n8"}, {"input": "1", "expected": "0"}, {"input": "2", "expected": "0\n1"}], ["Hai bien f0, f1 va cap nhat bang bien tam.", "In gia tri truoc khi tinh tiep."], "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    int f0 = 0, f1 = 1;\n    for (int i = 0; i < n; i++) {\n        cout << f0 << \"\\n\";\n        int t = f0 + f1;\n        f0 = f1;\n        f1 = t;\n    }\n    return 0;\n}", "Cap nhat tuyen tinh f0, f1 giu Fibonacci chay O(1) bo nho.", ["loops", "fibonacci", "practice"]],
    ["Tổng chữ số", "easy", "Doc so nguyen khong am va in tong cac chu so cua no.", "#include <iostream>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "123", "expected": "6"}, {"input": "905", "expected": "14"}, {"input": "0", "expected": "0"}], ["n % 10 lay chu so cuoi.", "n /= 10 bo chu so."], "#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    int s = 0;\n    while (n > 0) {\n        s += n % 10;\n        n /= 10;\n    }\n    cout << s;\n    return 0;\n}", "% 10 va / 10 la bo doi chuẩn để tách từng chữ số.", ["loops", "digits", "practice"]],
    ["Mã Caesar", "hard", "Doc mot tu chu thuong va so dich k (0-25). Dich moi ky tu trong bang chu cai (quay vong z -> a) roi in ket qua.", "#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    // Viet loi giai cua ban tai day\n    return 0;\n}", [{"input": "abc 1", "expected": "bcd"}, {"input": "xyz 3", "expected": "abc"}, {"input": "dog 0", "expected": "dog"}, {"input": "z 1", "expected": "a"}], ["(c - 'a' + k) % 26 + 'a'.", "% 26 tao hieu ung quay vong."], "#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string s;\n    int k;\n    cin >> s >> k;\n    for (char &c : s)\n        c = (char)('a' + (c - 'a' + k) % 26);\n    cout << s;\n    return 0;\n}", "Chuyen ky tu ve so 0-25, dich, roi % 26 de quay vong - lop co so cua ma hoa.", ["strings", "char", "modulo", "practice"]],
  ]);
  window.cppExercises = exercises;
})();
